import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

final appLanguage = ValueNotifier<String>('system');

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('zh')];

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations) ??
      AppLocalizations(
        Localizations.maybeLocaleOf(context) ?? const Locale('en'),
      );

  String text(String key) =>
      (_values[locale.languageCode] ?? _values['en']!)[key] ??
      _values['en']![key] ??
      key;

  String status(String? value) => text(value ?? 'clear');
  String diagnosis(String kind) => text('diagnosis_$kind');

  /// Localized label for a per-language diagnosis reason (e.g. `tone_confusion`).
  /// Unknown reasons degrade to their raw name so a new language's reason never
  /// breaks rendering.
  String diagnosisReason(String name) {
    final key = 'diagnosis_reason_$name';
    final localized = text(key);
    return localized == key ? name : localized;
  }

  /// Localized short hint for an L1 difficulty category (Phase 3.9). Falls
  /// back to [fallback] (the profile's neutral English explanation) so a new
  /// category never renders as a raw key.
  String l1Difficulty(String kind, String fallback) {
    final key = 'l1_difficulty_$kind';
    final localized = text(key);
    return localized == key ? fallback : localized;
  }

  /// Localized category name for an L1 difficulty kind.
  String l1DifficultyName(String kind) {
    final key = 'l1_difficulty_name_$kind';
    final localized = text(key);
    return localized == key ? kind.replaceAll('_', ' ') : localized;
  }

  static const delegate = _AppLocalizationsDelegate();

  static const _values = <String, Map<String, String>>{
    'en': {
      'settings': 'Settings',
      'moreActions': 'More actions',
      'playbackSettings': 'Playback settings',
      'general': 'General',
      'resourceSettings': 'Resources',
      'externalToolsShort': 'External tools',
      'rate': 'Playback speed',
      'language': 'Language',
      'system': 'Follow system',
      'english': 'English',
      'chinese': '简体中文',
      'japanese': '日本語',
      'learningLanguage': 'Learning language',
      'l1Language': 'Native language (L1)',
      'l1LanguageHint':
          'Used only to explain listening difficulties from your L1 habits; leave unset for neutral diagnosis.',
      'l1NotSet': 'Not set',
      'l1HintsTitle': 'From your native-language ear',
      'l1UnsupportedPair':
          'No L1-aware content for this language pairing yet; baseline diagnosis shown.',
      'l1ListenAgain': 'Listen again',
      'l1SimilarClips': 'Similar clips',
      'l1SpecialtyPractice': 'Practice this sentence',
      'l1SpecialtyUnindexed':
          'Corpus index not built; showing clips from the current media only.',
      'l1SpecialtyEmpty': 'No matching clips in your material yet.',
      'l1_difficulty_name_weak_function_words': 'Weak function words',
      'l1_difficulty_name_schwa_reduction': 'Reduced vowels (schwa)',
      'l1_difficulty_name_final_consonants': 'Final consonants',
      'l1_difficulty_name_consonant_clusters': 'Consonant clusters',
      'l1_difficulty_name_t_d_deletion': 't/d deletion',
      'l1_difficulty_name_flapping': 'Flapping',
      'l1_difficulty_name_linking': 'Linking',
      'l1_difficulty_name_stress_timed_rhythm': 'Stress-timed rhythm',
      'l1_difficulty_name_compressed_forms': 'Compressed forms',
      'subtitles': 'Subtitles',
      'subtitlePreset': 'Subtitle preset',
      'watching': 'Watching',
      'learning': 'Learning',
      'compact': 'Compact',
      'subtitleScale': 'Primary font size',
      'secondaryScale': 'Secondary font size',
      'primaryFont': 'Primary font',
      'secondaryFont': 'Secondary font',
      'systemFont': 'System font',
      'serifFont': 'Serif',
      'monospaceFont': 'Monospace',
      'horizontalPosition': 'Horizontal position',
      'verticalPosition': 'Vertical position',
      'resetSubtitlePosition': 'Reset subtitle position',
      'dragSubtitleHint': 'Drag the subtitle to move it',
      'backgroundOpacity': 'Background opacity',
      'transcriptWidth': 'Transcript width',
      'primaryColor': 'Primary color',
      'secondaryColor': 'Secondary color',
      'externalTools': 'Optional external tools',
      'close': 'Close',
      'save': 'Save',
      'vocabulary': 'Vocabulary',
      'listeningDictionary': 'Listening Dictionary',
      'openListeningDictionary': 'Listen in dictionary',
      'dictionaryWord': 'Learning word',
      'dictionaryPhrase': 'Learning phrase',
      'dictionaryClips': 'Your source clips',
      'dictionaryCoverage': 'Only {count} clip(s) in your library',
      'dictionaryNoClips': 'No source clips yet',
      'dictionaryNoClipsHint':
          'Open {word} from a subtitle while listening to save its first source clip.',
      'dictionaryRevealSentence': 'Reveal sentence text',
      'dictionaryClipReady': 'Ready to play',
      'dictionaryClipNeedsSource': 'Source file needs locating',
      'dictionaryPlayClip': 'Play source clip',
      'dictionaryHeard': 'Heard it',
      'dictionaryNotHeard': 'Did not hear it',
      'dictionaryMarkedHeard': 'Marked: heard it',
      'dictionaryMarkedNotHeard': 'Marked: did not hear it',
      'dictionaryMarkUnavailable':
          'This older clip has no durable sentence link, so it cannot add evidence.',
      'dictionaryMarkFailed': 'Could not save this marking: {error}',
      'dictionaryLibrarySection': 'More from my library',
      'dictionaryFindMore': 'Search my library',
      'dictionaryNoLibraryResults': 'No other contexts in your library yet',
      'dictionaryCollect': 'Save as source clip',
      'dictionaryCollected': 'Saved as a source clip of this entry',
      'dictionaryCollectFailed': 'Could not save this clip: {error}',
      'corpusKindWord': 'Word',
      'corpusKindSentence': 'Sentence',
      'corpusKindChunk': 'Chunk',
      'dictionaryReindex': 'Rebuild library index',
      'dictionaryReindexDone': 'Reindexed {count} subtitle tracks',
      'dictionaryReindexFailed': 'Could not rebuild the index: {error}',
      'dictionaryAddToReview': 'Add to review',
      'dictionaryReviewQueued': 'Added to sound review',
      'dictionaryReviewFailed': 'Could not add to review: {error}',
      'dictionaryReviewClip': 'Add this clip to review',
      'huntingList': 'Hunting List',
      'huntingTargetCount': '{count} of 5 active targets',
      'huntingActiveTargets': 'Currently attacking',
      'huntingReviewCandidates': 'From repeated review misses',
      'huntingNoTargets':
          'No active targets. Add a word or phrase from its dictionary page.',
      'huntingNoCandidates': 'No review-failure candidates waiting.',
      'huntingAdd': 'Add',
      'huntingAdded': 'Added to Hunting List',
      'huntingAlreadyAdded': 'Already in Hunting List',
      'huntingArchived': 'Removed from active targets',
      'huntingUpdateFailed': 'Could not update Hunting List: {error}',
      'huntingArchive': 'Remove from active targets',
      'huntingSourceManual': 'Added from the listening dictionary',
      'huntingSourceReview': 'Confirmed after repeated review misses',
      'huntingSourceInbox': 'Confirmed from Listening Inbox',
      'huntingFailureCount': 'Missed in review {count} time(s)',
      'huntingOpen': 'Open Hunting List',
      'huntingAddCurrent': 'Add to Hunting List',
      'huntingStartMode': 'Start Hunting Mode',
      'huntingStopMode': 'Stop Hunting Mode',
      'huntingStarted': 'Hunting Mode ready: {count} occurrence(s)',
      'huntingStopped': 'Hunting Mode stopped',
      'huntingIndexNeeded':
          'This media has no corpus index yet. Rebuild it to locate targets.',
      'huntingListenFor': 'Listen for “{target}”',
      'huntingDidYouHear': 'Did you hear “{target}”?',
      'huntingAnswerYes': 'Yes',
      'huntingAnswerNo': 'No',
      'huntingAnswerNotNoticed': 'Did not notice',
      'huntingAnswerSaved': 'Hunting check saved',
      'dictionarySortDefault': 'Recent',
      'dictionarySortByRate': 'By speech rate',
      'dictionaryWpm': '≈{wpm} wpm',
      'dictionaryExternalHint': 'Outside your library (reference only):',
      'dictionaryYouglish': 'Open on YouGlish',
      'dictionarySampledHint':
          'Large entry: sampled across media, showing the first {count}',
      'dictionaryContentSection': 'My definition & note',
      'dictionarySenseFolders': 'Meaning folders',
      'dictionarySenseFoldersHint':
          'Optional personal organization. Source clips do not need a folder.',
      'dictionaryNoSenseFolders': 'No meaning folders yet',
      'dictionaryAddSenseFolder': 'Add meaning folder',
      'dictionaryEditSenseFolder': 'Edit meaning folder',
      'dictionarySenseFolderLabel': 'Meaning label',
      'dictionarySenseFolderDefinition': 'Definition (optional)',
      'dictionarySenseFolderGloss': 'Gloss (optional)',
      'dictionarySenseFolderExternalRef': 'External reference (optional)',
      'dictionarySenseFolderClipCount': '{count} clip(s)',
      'dictionarySenseFolderEmpty': 'No clips assigned yet',
      'dictionaryUnassignedClips': 'Unassigned clips',
      'dictionaryAssignSenseFolder': 'Assign meaning',
      'dictionaryAssignedSenseFolder': 'Change meaning',
      'dictionaryUnassignSenseFolder': 'Remove from {label}',
      'dictionaryContentSaved': 'Definition and note saved',
      'dictionaryUpdateFailed': 'Could not update: {error}',
      'dictionaryUpgradeSuggestion':
          'Listening evidence from {count} contexts suggests you can hear this now.',
      'home': 'Home',
      'library': 'Library',
      'listenNow': 'Listen',
      'myLearning': 'My learning',
      'continueLearning': 'Continue learning',
      'continuePlayback': 'Continue',
      'noRecentMedia': 'No recent media yet',
      'openMediaToContinue': 'Open local media to start or resume listening.',
      'subtitleReadiness': 'Subtitles',
      'notReadyYet': 'Not ready',
      'savedWords': 'Saved words',
      'localCore': 'Local core',
      'coreReady': 'Ready',
      'startListening': 'Start listening',
      'learningTools': 'Learning tools',
      'contentActions': 'Content',
      'subtitleActions': 'Subtitles',
      'learningActions': 'Learning',
      'localSource': 'Video or audio from this Mac',
      'onlineSource': 'Open a supported online address',
      'subtitleResourceSummary': 'Subtitles and timeline resources',
      'vocabularySummary': 'Words and phrases saved while listening',
      'review': 'Review',
      'coachDashboard': 'Coach',
      'coachDashboardSummary': 'Diagnosis and next-step suggestions',
      'coachThisWeek': 'Listening evidence · last 7 days',
      'coachNextSteps': 'Suggested next steps',
      'coachNoSuggestions':
          'Keep listening and practicing. Suggestions will appear as evidence grows.',
      'coachStarter': 'Build your first evidence',
      'coachUnassessed': 'Not assessed yet — no active validation',
      'coachSuggestionReview': 'Review due audio cards',
      'coachSuggestionReviewReason': 'Due schedules are waiting',
      'coachSuggestionHunting': 'Confirm repeated listening misses',
      'coachSuggestionHuntingReason':
          'Review failures created hunting candidates',
      'coachSuggestionSpecialty': 'Revisit L1-aware listening patterns',
      'coachSuggestionSpecialtyReason':
          'Rule-based difficulty hits were recorded; they are hints, not audio proof',
      'coachSuggestionContinue': 'Continue with real listening input',
      'coachSuggestionContinueReason':
          'Recent extensive sessions provide a stable baseline',
      'coachStarter_complete_extensive_listening':
          'Finish one extensive listening session',
      'coachStarter_complete_active_practice':
          'Complete one cloze or dictation attempt',
      'coachStarter_review_due_items': 'Review any due audio cards',
      'coachMetric_extensive_sessions': 'Extensive sessions',
      'coachMetric_extensive_listening_ms': 'Extensive listening',
      'coachMetric_practice_attempts': 'Active practice attempts',
      'coachMetric_correct_practice_attempts': 'Correct practice attempts',
      'coachMetric_review_attempts': 'Review attempts',
      'coachMetric_successful_review_attempts': 'Successful reviews',
      'coachMetric_listening_capability_changes':
          'Listening capability changes',
      'coachMetric_l1_difficulty_hits': 'L1-aware rule hits',
      'coachMaterials': 'Material progress',
      'coachMaterialTrajectory': 'Comprehension reports',
      'coachGraduate': 'Mark graduated',
      'coachGraduateConfirmTitle': 'Graduate this material?',
      'coachGraduateConfirmBody':
          'This only organizes your library. It does not automatically change any language capability.',
      'coachEvidenceSource': 'Durable source',
      'coachEvidenceCount': 'Facts in period',
      'coachEvidenceEmpty': 'No source facts in this period.',
      'coachReport_understood_all': 'understood all',
      'coachReport_got_the_gist': 'got the gist',
      'coachReport_unclear': 'unclear',
      'coachReport_unknown': 'not reported',
      'queueGraduated': 'Graduated',
      'coachIntent_pin_intensive': 'Move to intensive',
      'coachIntent_pin_extensive': 'Keep for extensive',
      'coachMaterialAdjustTitle': 'Adjust this material?',
      'coachMaterialAdjustBody':
          'This suggestion follows your repeated comprehension reports. Confirming only changes the library queue.',
      'audioFirstReview': 'Audio-first due cards',
      'noMediaSelected': 'No media selected',
      'backToHome': 'Home',
      'expandWorkbench': 'Expand',
      'openMedia': 'Open media',
      'openUrl': 'Open URL',
      'primarySubtitle': 'Primary subtitle',
      'secondarySubtitle': 'Secondary subtitle',
      'noSecondarySubtitle': 'No secondary subtitle',
      'transcript': 'Transcript',
      'wordLearning': 'Word learning',
      'diagnosis': 'Diagnosis',
      'practice': 'Practice',
      'understandPosture': 'Understand?',
      'testPosture': 'Test?',
      'shadowPosture': 'Shadow?',
      'shadowingPlannedTooltip': 'Shadowing and recording arrive in Phase 3.8.',
      'shadowingReadyTooltip':
          'Follow the current rhythm chunk and compare your recording.',
      'shadowingPractice': 'Shadowing',
      'shadowingSpeed': 'Original audio speed',
      'shadowingPlayOriginal': 'Play original',
      'shadowingStartRecording': 'Start recording',
      'shadowingStopRecording': 'Stop and compare',
      'shadowingRecordAgain': 'Record again',
      'shadowingRecordingActive':
          'Recording locally… original audio is paused.',
      'shadowingPermissionDenied':
          'Microphone access is disabled. Enable it in macOS Privacy & Security.',
      'openSystemSettings': 'Open Settings',
      'shadowingComparison': 'Objective comparison · no score',
      'shadowingPlayMine': 'Play mine',
      'shadowingOriginal': 'Original',
      'shadowingMine': 'Mine',
      'shadowingDurationDelta': 'Duration difference',
      'shadowingSameDuration': 'same duration',
      'shadowingPauseCount': 'pauses original / mine',
      'shadowingPauseOffset': 'mean pause offset',
      'selectWordFromTranscript':
          'Select a word in the transcript to see status, meaning, and source examples.',
      'diagnosisUnavailable': 'No listening reference yet',
      'openSentenceDiagnosisHint':
          'Load subtitles, then open a sentence to see vocabulary status and sound references.',
      'clozePractice': 'Cloze',
      'chunkDictation': 'Chunk dictation',
      'sentenceDictation': 'Sentence dictation',
      'practiceClozeTooltip': 'Blank a known word and verify it by ear.',
      'practiceClozeUnavailable': 'Cloze needs word-level timing.',
      'practiceChunkTooltip': 'Type the current chunk from audio.',
      'practiceChunkFallbackTooltip':
          'No active chunk here; this falls back to the sentence.',
      'practiceNeedsSentence': 'Open a subtitle sentence to practice.',
      'practiceChoosePrompt': 'Choose cloze or dictation for this sentence.',
      'practiceWindow': 'Practice',
      'practiceProgress': 'Sentence {current} of {total}',
      'practicePlayer': 'Current sentence',
      'practicePlayerHint': 'Replay, pause, or move to an adjacent sentence.',
      'hidePracticePlayer': 'Hide player',
      'showPracticePlayer': 'Show player',
      'practiceEstimatedTiming':
          'Timing is estimated; the replay window may be approximate.',
      'practiceListenThenType': 'Listen, then type what you heard.',
      'practiceHiddenText': 'The answer stays hidden until you submit.',
      'practiceAnswer': 'Answer',
      'createReviewOnFailure': 'Save a failed attempt to review',
      'submit': 'Submit',
      'replay': 'Replay',
      'retryPractice': 'Try again',
      'openDiagnosis': 'Load reference',
      'saveToReview': 'Save to review',
      'savedToReview': 'Saved to review',
      'practiceResult': 'Result',
      'practiceCorrect': 'correct',
      'practicePartial': 'partly matched',
      'practiceIncorrect': 'not yet',
      'practiceSkipped': 'skipped',
      'startExtensiveListening': 'Start extensive listening',
      'finishExtensiveListening': 'Finish extensive listening',
      'listeningMode': 'Listening',
      'extensiveListeningActive': 'Extensive listening is active',
      'extensiveListeningIdle': 'Extensive listening is idle',
      'markListeningInbox': 'Mark Listening Inbox',
      'hardInterruptListening': 'Pause and inspect',
      'listeningInbox': 'Listening Inbox',
      'listeningInboxEmpty': 'No marked listening moments yet.',
      'comprehensionReportPrompt': 'How much did this session make sense?',
      'huntingCompletionSummary':
          'Hunting: {prompted} prompts / {recognized} recognized',
      'skipReport': 'Skip',
      'reportUnderstoodAll': 'All clear',
      'reportGist': 'Got the gist',
      'reportUnclear': 'Unclear',
      'microIntensive': 'Micro intensive',
      'favoriteSegment': 'Favorite segment',
      'dismissInboxItem': 'Archive',
      'expected': 'Expected',
      'youTyped': 'You typed',
      'possibleWhy': 'Possible reason',
      'noWordSelected': 'Click a subtitle word to open its learning details.',
      'dictionary': 'Dictionary',
      'noDictionary': 'No dictionary result',
      'userDefinition': 'Your definition',
      'personalNote': 'Personal note',
      'sources': 'Sources',
      'statusHistory': 'Status history',
      'currentStatus': 'Current status',
      'learningState': 'Learning state',
      'meaningAndPronunciation': 'Meaning and pronunciation',
      'sourceSentences': 'Source sentences',
      'learningHistory': 'Learning history',
      'noSourceSentences': 'No source sentence recorded yet.',
      'recordCurrentSentence': 'Record current',
      'noLearningHistory': 'No learning history yet.',
      'earlier': 'Earlier',
      'clear': 'Clear',
      'unknown_meaning': 'Unknown meaning',
      'known_not_recognized': 'Known, not recognized',
      'known_recognized': 'Known and recognized',
      'unassessed': 'Not yet assessed',
      'not_acquired': 'Not acquired',
      'acquired': 'Acquired',
      'capabilityReading': 'Reading',
      'capabilityListening': 'Listening',
      'capabilitySpeaking': 'Speaking',
      'capabilityWriting': 'Writing',
      'capabilityProfile': 'Capability profile',
      'listeningUpgradeSuggestion':
          '"{word}" heard in {count} contexts — mark listening as acquired?',
      'confirmListeningAcquired': 'Confirm: can hear it',
      'deferUpgrade': 'Not yet',
      'apply': 'Apply',
      'heard': 'This sentence: heard',
      'notHeard': 'This sentence: not heard',
      'importWordList': 'Import word list',
      'importAssets': 'Import vocabulary assets',
      'exportAssets': 'Export vocabulary assets',
      'overwriteExisting': 'Overwrite existing classified words',
      'previewImport': 'Import preview',
      'import': 'Import',
      'noWords': 'No words in this book',
      'searchVocabulary': 'Search vocabulary',
      'vocabFilterAll': 'All',
      'vocabFilterCapabilityHint': 'Filter by a capability channel',
      'vocabularyBooks': 'Vocabulary books',
      'loopSentence': 'Loop sentence',
      'previousChunk': 'Previous chunk',
      'nextChunk': 'Next chunk',
      'chunkMode': 'Chunks',
      'loopChunk': 'Loop chunk',
      'expandChunk': 'Expand chunk',
      'subtitleMode': 'Subtitle',
      'chunkReplayUnavailableControl':
          'Chunk replay needs an active chunk for the current sentence.',
      'wordStyles': 'Word styles',
      'secondary': 'Secondary',
      'secondarySubtitleUnavailable': 'Load a secondary subtitle track first.',
      'noMediaControlsHint': 'Open media to enable playback controls',
      'taskSubtitleGeneration': 'Subtitle generation',
      'taskAudioAnalysis': 'Phone evidence analysis',
      'taskStateWorking': 'Working',
      'taskStateSuccess': 'Done',
      'taskStateWarning': 'Needs attention',
      'taskStateError': 'Failed',
      'taskStateCancelled': 'Cancelled',
      'taskStateUnknown': 'Unknown',
      'currentSentenceDiagnosis': 'Listening reference',
      'pronunciationProvider': 'Pronunciation provider',
      'wordTimingSource': 'Word timing source',
      'pronunciationCache': 'Pronunciation cache',
      'cacheReusable': 'reusable',
      'ready': 'ready',
      'degraded': 'degraded',
      'providerUnavailable': 'Provider unavailable',
      'noSourceSnapshot': 'No source snapshot',
      'encountered': 'encountered',
      'times': 'times',
      'openOnlineTitle': 'Open online media with yt-dlp',
      'pageUrl': 'Page URL',
      'addSource': 'Add source',
      'pasteSourceLink': 'Paste a video or audio link',
      'recognizedSource': 'Recognized source',
      'youtubeSource': 'YouTube',
      'webSource': 'Web address',
      'playOnline': 'Play online',
      'downloadLocal': 'Download to this Mac',
      'sourceAuthorizationNotice':
          'Only add content you are authorized to access. Provider terms still apply.',
      'invalidSourceUrl': 'Enter a valid http or https address.',
      'cancel': 'Cancel',
      'resolvePlay': 'Resolve and play',
      'download': 'Download',
      'downloadVideo': 'Download video',
      'downloadHere': 'Download here',
      'startingDownload': 'Starting download...',
      'downloadingVideo': 'Downloading video',
      'downloadComplete': 'Download complete',
      'downloadFailed': 'Download failed',
      'downloadCancelled': 'Download cancelled',
      'downloadingInBackground': 'Downloading in background',
      'openDownloadedVideo': 'Open downloaded video',
      'importEmbeddedText': 'Import embedded text subtitle',
      'usePrimary': 'Use as primary',
      'useSecondary': 'Use as secondary',
      'exportLogs': 'Export logs',
      'archiveMedia': 'Archive current media',
      'openVideoAudio': 'Open video or audio',
      'importSubtitle': 'Import subtitle',
      'importSubtitleHint': 'Import SRT or WebVTT subtitles',
      'noTranscriptTitle': 'No transcript yet',
      'backToCurrentSentence': 'Back to current',
      'subtitleResources': 'Subtitle resources',
      'contentFit': 'Difficulty',
      'contentFitMeaning': 'Vocabulary',
      'contentFitSound': 'Sound',
      'fit_too_easy': 'Easy',
      'fit_comprehensible': 'Comfortable',
      'fit_challenging': 'Challenging',
      'fit_too_hard': 'Demanding',
      'contentFitIntensiveTarget':
          'You can likely follow the text, but decoding by ear will be the work — good intensive listening material.',
      'contentFitInitialEstimate': 'Initial estimate',
      'contentFitCalibrated': 'Calibrated by your usage',
      'contentFitLowProfile':
          'Your vocabulary profile covers little of this transcript yet, so this is a conservative guess. Marking a few words will sharpen it.',
      'coldStartQuickMarking': 'Quick marking',
      'coldStartEmpty': 'No high-frequency words to mark right now.',
      'coldStartProgress': '{current} / {total}',
      'coldStartKnownRecognized': 'Know it & hear it',
      'coldStartKnownNotRecognized': 'Know it, can\'t hear it',
      'coldStartUnknownMeaning': 'Don\'t know it',
      'coldStartSkip': 'Skip',
      'mediaLibrary': 'Media library',
      'mediaLibraryEmpty': 'Media you open will appear here.',
      'queueIntensive': 'Intensive picks',
      'queueExtensive': 'Extensive listening',
      'queueDeferred': 'Set aside for now',
      'queueUnsorted': 'Not rated yet',
      'goldenTargetBadge': 'Intensive pick',
      'familiarRelistenBadge': 'Relisten',
      'startExtensiveAction': 'Listen',
      'startIntensiveAction': 'Work on it',
      'pinExtensiveAction': 'Pin to extensive listening',
      'pinIntensiveAction': 'Pin to intensive picks',
      'deferMediaAction': 'Set aside',
      'clearTriageAction': 'Clear pin / set-aside',
      'familiarSuggestionsToggle': 'Suggest relistening familiar material',
      'mediaFileMissing': 'File not found',
      'contentFitWhy': 'Why this rating',
      'contentFitDecisive': 'Drove the rating',
      'fit_signal_unknown_meaning_density': 'Unknown-meaning words',
      'fit_signal_unassessed_density': 'Words not assessed yet',
      'fit_signal_known_not_recognized_density':
          'Known but not yet caught by ear',
      'fit_signal_speech_rate_wpm': 'Speech rate',
      'fit_signal_weak_form_density': 'Weak-form density',
      'fit_signal_compression_density': 'Compression density',
      'fit_signal_mean_chunk_length': 'Average chunk length',
      'fit_signal_comprehension_report_unclear_ratio':
          'Sessions you reported as unclear',
      'fit_signal_practice_correct_rate': 'Your practice accuracy',
      'noSubtitleResources': 'No subtitle resources yet',
      'activeSubtitle': 'Active subtitle',
      'activateSubtitle': 'Activate subtitle',
      'sentenceTiming': 'Sentence',
      'wordTiming': 'Word',
      'chunkTiming': 'Chunk',
      'phoneTiming': 'Phone',
      'resourcePartial': 'Partial',
      'resourceLearningCapabilities': 'Learning capabilities',
      'resourceReady': 'Ready to use',
      'resourceArchived': 'Archived',
      'technicalDetails': 'Technical details',
      'resourceTimelineDetailsBelow': 'Details below',
      'resourceActivateToInspect': 'Activate to inspect',
      'diagnosisSummary': 'Summary',
      'diagnosisEvidence': 'Evidence and analysis',
      'diagnosisNoConclusion': 'No specific listening barrier identified.',
      'resourceActions': 'Resource actions',
      'archiveResource': 'Archive resource',
      'restoreResource': 'Restore resource',
      'deleteResource': 'Delete resource',
      'exportSubtitle': 'Export subtitle',
      'exportSubtitleFormat': 'Export subtitle format',
      'exportLLTimelineJson': 'Export LLTimeline JSON',
      'deleteSubtitleResourceBody':
          'Delete this subtitle resource and its attached timelines from the local library?',
      'cues': 'cues',
      'timelineFingerprintMismatch': 'Timeline media mismatch',
      'timelineFingerprintMismatchBody':
          'This LLTimeline resource was produced for a different media fingerprint. Attach it only if you know it matches the current media.',
      'attachAnyway': 'Attach anyway',
      'previousSentence': 'Previous sentence',
      'nextSentence': 'Next sentence',
      'restartMedia': 'Restart media',
      'playPause': 'Play / pause',
      'stop': 'Stop',
      'stopSourceLoop': 'Stop loop',
      'loopRange': 'Range loop',
      'loopReview': 'Review loop',
      'loopPractice': 'Practice loop',
      'loopInbox': 'Inbox loop',
      'loopRhythm': 'Rhythm loop',
      'loopPhone': 'Phoneme loop',
      'loopHotspot': 'Hotspot loop',
      'slicePlayback': 'Source clip',
      'slicePlaybackAudioFirst': 'Audio-first source clip',
      'slicePlaybackInvalidRange': 'This source clip has an invalid time range',
      'slicePlaybackNoSentence': 'No source sentence snapshot is available.',
      'slicePlaybackSourceMedia': 'Source media',
      'slicePlaybackReplay': 'Replay clip',
      'slicePlaybackPause': 'Pause',
      'slicePlaybackPlay': 'Play',
      'slicePlaybackLooping': 'Looping clip',
      'slicePlaybackPlayOnce': 'Play once',
      'slicePlaybackShowVideo': 'Show video',
      'slicePlaybackHideVideo': 'Hide video',
      'compactMediaPane': 'Compact media pane',
      'resetWorkbenchLayout': 'Reset media/transcript split',
      'audioTrack': 'Audio track',
      'embeddedSubtitles': 'Embedded subtitles',
      'primaryOffset': 'Primary offset',
      'secondaryOffset': 'Secondary offset',
      'generateSubtitles': 'Generate subtitles',
      'generateWholeMedia': 'Generate whole media',
      'primarySubtitleGenerationStarted':
          'Subtitle generation started. The generated primary subtitles will load when the job completes.',
      'secondarySubtitleGenerationStarted':
          'Subtitle generation started. The generated secondary subtitles will load when the job completes.',
      'loadingGeneratedPrimarySubtitle':
          'Loading generated primary subtitles...',
      'generatedPrimarySubtitleLoaded': 'Generated primary subtitles loaded',
      'generatedSecondarySubtitleLoaded':
          'Generated secondary subtitles loaded',
      'generatedSubtitleResourceWarning':
          'Some learning resources need attention',
      'generatePrimaryHint':
          'The completed track will be available as the primary subtitle.',
      'generateSecondaryHint':
          'The completed track will be available as the secondary subtitle.',
      'transcriptionCenter': 'ASR models and jobs',
      'models': 'Models',
      'model': 'Model',
      'jobs': 'Jobs',
      'modelRequired': 'A transcription model is required',
      'installModelFirst':
          'Open ASR models and jobs, then install or register a compatible model.',
      'transcriptionLanguage': 'Recognition language',
      'automatic': 'Automatic detection',
      'translateEnglish': 'Translate speech to English',
      'multilingual': 'Multilingual',
      'registerCustomModel': 'Register custom model',
      'install': 'Install',
      'syntaxCapabilityTitle': 'Local syntax enhancement',
      'syntaxCapabilityDescription':
          'Optional local grammar analysis improves selected connected-speech and semantic grouping hints. It is never required for playback or subtitles.',
      'syntaxCoreUnavailable': 'Local core unavailable',
      'syntaxCancel': 'Cancel',
      'syntaxVerify': 'Verify',
      'syntaxUpdate': 'Update',
      'syntaxDisable': 'Disable',
      'syntaxEnable': 'Enable',
      'syntaxUninstall': 'Uninstall',
      'syntaxRebuild': 'Rebuild',
      'syntaxTrackBackground':
          'Current track analysis runs quietly in the background.',
      'syntaxCacheReused': 'reused cache',
      'syntaxSentences': 'sentences',
      'syntaxNotInstalled': 'not installed',
      'syntaxDownloading': 'downloading',
      'syntaxReady': 'ready',
      'syntaxPartial': 'partial',
      'syntaxFailed': 'failed',
      'syntaxStale': 'update required',
      'syntaxDisabled': 'disabled',
      'remove': 'Remove',
      'archive': 'Archive',
      'retry': 'Retry',
      'noTranscriptionJobs': 'No transcription jobs',
      'loadGeneratedSubtitle': 'Load generated subtitle',
      'transcriptionDefaults': 'Transcription defaults',
      'phoneticAnalysis': 'Experimental audio detection',
      'phoneticAnalysisCenter': 'Audio analysis models and jobs',
      'experimental': 'Experimental',
      'llmProviders': 'AI providers',
      'llmProvidersDescription':
          'Vendor-neutral LLM providers for optional semantic feedback. You choose your own cloud or local model; core learning keeps working without one.',
      'llmDataWarning':
          'Text you have judged (transcripts and subtitles) is sent to the endpoint you configure. For custom endpoints, how that data is handled is decided by that server.',
      'llmNotQualified':
          'Not qualified for display: any judgment here is diagnostic only and does not appear as learning feedback until independently qualified.',
      'llmNoProviders': 'No providers configured yet.',
      'llmAddProvider': 'Add a provider',
      'llmAdapterKind': 'Protocol',
      'llmDisplayName': 'Name',
      'llmBaseUrl': 'Base URL',
      'llmModelId': 'Model',
      'llmApiKey': 'API key (write-only)',
      'llmApiKeyHint':
          'Stored in the system keychain by the backend. Not shown again.',
      'llmAllowedUses': 'Allowed uses',
      'llmUseJudgment': 'Semantic judgment',
      'llmUseRubric': 'Rubric generation',
      'llmRegister': 'Save provider',
      'llmTest': 'Test',
      'llmRemove': 'Remove',
      'llmKeyStored': 'Key stored',
      'llmProbing': 'Testing…',
      'llmProbeSupported': 'Structured output: supported',
      'llmProbeUnsupported': 'Structured output: not supported',
      'llmProbeFailed': 'Test failed',
      'llmSidecarUnavailable': 'Connect the backend to manage AI providers.',
      'applicationVerified': 'Application verified',
      'notApplicationVerified': 'Not application verified',
      'distributionAllowed': 'Distribution allowed',
      'distributionNotAllowed': 'Distribution not allowed',
      'noPhoneticAnalysisJobs': 'No audio analysis jobs',
      'clearCompleted': 'Clear completed',
      'deleteJob': 'Delete',
      'jobCompleted': 'Completed',
      'jobFailed': 'Failed',
      'jobCancelled': 'Cancelled',
      'jobInterrupted': 'Interrupted',
      'jobQueued': 'Queued',
      'jobExtracting': 'Extracting audio',
      'jobRecognizingPhones': 'Recognizing phones',
      'jobAligning': 'Aligning',
      'jobAnalyzing': 'Analyzing',
      'confirmClearJobs': 'Clear all completed, failed, and cancelled jobs?',
      'confirmDeleteJob': 'Delete this job?',
      'phoneticAnalysisPreference': 'Analysis preference',
      'phoneticOnDemand': 'On demand',
      'phoneticBatch': 'Batch analysis',
      'disabled': 'Disabled',
      'phonemeRibbonVisible': 'Show text phoneme ribbon',
      'soundPatternRibbonVisible': 'Show sound reference',
      'soundPatternDisplayMode': 'Sound reference',
      'rhythmReferenceCitation': 'A · Dictionary',
      'rhythmReferenceConnected': 'B · Predicted audible',
      'rhythmReferenceActual': 'C · Actual audible',
      'rhythmReferenceCitationTooltip':
          'A · Dictionary pronunciation and lexical stress',
      'rhythmReferenceConnectedTooltip':
          'B · How dictionary word boundaries may reorganize in connected speech',
      'rhythmReferenceActualTooltip':
          'C · Audible groups supported by phones, timing and prosody in this audio',
      'showFullSoundStructure': 'Show full sentence',
      'collapseSoundStructure': 'Follow current position',
      'connectedSpeechReference': 'Predicted audible',
      'connectedSpeechReferenceTooltip':
          'A → B: written word boundaries compared with the sound groups predicted by language rules.',
      'connectedSpeechUnavailable': 'No predicted audible change for this line',
      'citationPronunciationUnavailable':
          'No dictionary pronunciation for this line',
      'showPhoneEvidence': 'Show phone evidence',
      'hidePhoneEvidence': 'Hide phone evidence',
      'phonemeRibbonStyle': 'Ribbon display style',
      'phonemeRibbonWindow': 'Sliding window',
      'phonemeRibbonWave': 'Wave magnification',
      'textPhonemeRibbonHint':
          'Text line: stable teaching phones from the subtitle words.',
      'soundPatternRibbonHint':
          'Listening layer: structure first, phone evidence as detail.',
      'soundPatternUnavailable': 'No phone evidence for this line',
      'soundPatternUnavailableTooltip':
          'Phone evidence appears after audio analysis or an imported timeline provides it for the current sentence.',
      'rhythmFrameUnavailable': 'No listening structure for this line',
      'rhythmRibbonHint':
          'Heard structure: meaning anchors you can catch from this audio; faint weak groups recede into the path.',
      'expectedPronunciationReference': 'Expected',
      'expectedPronunciationTooltip':
          'Dictionary pronunciation reference for the current sentence.',
      'soundReferenceNoData': 'No sound reference for this audio yet',
      'loadCurrentSentence': 'Load this sentence',
      'loadWholeTrack': 'Load whole track',
      'soundReferenceLoadHint':
          'Loading this sentence is quick; loading the whole track means no '
          'waiting when you switch sentences.',
      'canonicalPronunciation': 'Canonical pronunciation',
      'rulePrediction': 'Rule prediction',
      'audioDetectionExperimental': 'Audio detection (experimental)',
      'listeningRhythm': 'Listening structure',
      'listeningPredictedBadge': 'predicted',
      'listeningPredictedTooltip':
          'Predicted from text, not measured from this audio. Listening structure becomes audio-supported once word timing, energy or pitch evidence exists.',
      'stressAnchors': 'Heard anchors',
      'weakGroups': 'Weak groups',
      'compressedSpans': 'Compressed',
      'listeningHotspots': 'Hotspots',
      'rhythmQuality': 'Rhythm confidence',
      'currentDetectedPhone': 'Current detected phone',
      'loopEvidence': 'Loop evidence',
      'feedbackConfirmed': 'Matches what I hear',
      'feedbackRejected': 'Inaccurate',
      'feedbackIgnored': 'Ignore',
      'preferredQuality': 'Preferred quality',
      'defaultDestination': 'Default subtitle destination',
      'exportSrt': 'Export SRT',
      'regenerate': 'Regenerate with current algorithms',
      'runtimeReady': 'Runtime ready',
      'learningAssets': 'Learning assets',
      'resources': 'Offline learning data',
      'words': 'Words',
      'phones': 'Phones',
      'chunks': 'Chunks',
      'phrases': 'Phrases',
      'word': 'Word',
      'phrase': 'Phrase',
      'phraseCandidates': 'Phrase candidates',
      'phraseCandidatesHint':
          'Review fixed expressions from the current subtitle sentence. Only phrases you save become learning assets.',
      'noPhraseCandidates': 'No phrase candidates in the current sentence.',
      'confirmPhrase': 'Save phrase',
      'openSubtitles': 'Search OpenSubtitles',
      'openSubtitlesApiKey': 'OpenSubtitles API key',
      'openMediaForSubtitles': 'Open a media file before searching subtitles.',
      'configureOpenSubtitlesNow':
          'Enter your OpenSubtitles API key to continue.',
      'search': 'Search',
      'title': 'Title',
      'filename': 'Filename',
      'mediaHash': 'Media hash',
      'lemmaCorrectionSaved': 'Lemma correction saved',
      'configureOpenSubtitles':
          'Configure an OpenSubtitles API key in Settings',
      'pronunciation': 'Play pronunciation',
      'pronunciationUnavailable': 'Pronunciation audio is unavailable.',
      'highlightCurrentWord': 'Highlight current word',
      'groupingMode': 'Grouping',
      'groupingModeHint': 'Unify how subtitle words are grouped.',
      'groupingModeOff': 'Off',
      'groupingModeProsodic': 'Prosodic',
      'groupingModeSemantic': 'Semantic',
      'groupingModeCompare': 'Compare',
      'senseGroupDataAvailable': 'Available',
      'senseGroupDataNotReady': 'Data not ready',
      'senseGroupDataNotReadyHint':
          'Semantic grouping data is not ready; subtitles fall back to word display',
      'groupingSemanticProvisional': 'Provisional marker (heuristic)',
      'groupingDivergenceHint': 'Meaning and delivery disagree here',
      'chunkDisplayStyle': 'Group display style',
      'chunkDisplayCapsule': 'Capsules',
      'chunkDisplaySpacing': 'Spacing only',
      'highlightCurrentChunk': 'Highlight current group',
      'chunkHighlightStyle': 'Current-group highlight style',
      'chunkHighlightBackground': 'Static background',
      'chunkHighlightBounce': 'Slow scale bounce',
      'chunkHighlightGlow': 'Slow glow',
      'wordHighlightStyle': 'Current-word highlight style',
      'wordHighlightBackground': 'Background highlight',
      'wordHighlightBounce': 'Scale bounce',
      'wordHighlightGlow': 'Glow',
      'wordHighlightIntensity': 'Current-word highlight intensity',
      'ruleHints': 'Rule hints',
      'ruleHintsOff': 'Off',
      'ruleHintsLikely': 'Likely only',
      'ruleHintsAll': 'All',
      'rulePredictionDisclaimer':
          'Rule predictions, not detections from the audio:',
      'diagnosis_meaning_barrier':
          'Unknown vocabulary may block understanding.',
      'diagnosis_recognition_barrier':
          'Known vocabulary was not recognized in this sentence.',
      'diagnosis_insufficient_information':
          'Classify the remaining words before drawing a conclusion.',
      'diagnosis_other_factors':
          'Vocabulary does not fully explain the listening difficulty.',
      'characters': 'Characters',
      'possibleListeningFactors': 'Factors to consider (not detected):',
      'diagnosis_reason_tone_confusion': 'tone confusion',
      'diagnosis_reason_word_boundary': 'word boundary',
      'diagnosis_reason_homophone': 'homophone',
      'diagnosis_reason_neutral_tone': 'neutral tone',
      'diagnosis_reason_tone_sandhi': 'tone sandhi',
      'diagnosis_reason_weak_form': 'weak form',
      'diagnosis_reason_linking': 'linking',
      'diagnosis_reason_elision': 'elision',
      'diagnosis_reason_assimilation': 'assimilation',
      'diagnosis_reason_fuzzy_boundary': 'fuzzy boundary',
      'diagnosis_reason_reduced_form': 'reduced form',
      'timelineResource': 'Timeline resource',
      'capabilityReadiness': 'Learning capabilities',
      'capabilityStateAvailable': 'Available',
      'capabilityStateGenerating': 'Generating',
      'capabilityStateDegraded': 'Degraded',
      'capabilityStateUnavailable': 'Unavailable',
      'capabilityStateUnsupported': 'Unsupported',
      'capabilityStateStale': 'Stale',
      'capabilityStateError': 'Error',
      'capabilitySubtitles': 'Subtitles',
      'capabilityWordSync': 'Word sync',
      'capabilityChunkReplay': 'Chunk replay',
      'capabilityListeningStructure': 'Listening structure',
      'capabilityPhoneEvidence': 'Phone evidence',
      'capSubtitlesAvailable': 'Active subtitle track loaded.',
      'capSubtitlesArchived': 'This active subtitle is archived.',
      'capSubtitlesUnavailable':
          'Import, generate, search, extract, or attach subtitles.',
      'capWordSyncAvailable': 'Word-level timing is active.',
      'capWordSyncEstimated':
          'Word timing is estimated; highlights may be approximate.',
      'capWordSyncUnavailableNoSubtitle':
          'Load subtitles before word sync can run.',
      'capWordSyncUnavailable':
          'Needs an active Word sync timeline or generated word timings.',
      'capWordSyncGeneratedTimings': 'Generated word timings are loaded.',
      'capChunkReplayAvailable': 'Chunk replay is ready.',
      'capChunkReplayUnavailableNoSubtitle':
          'Load subtitles before chunk replay can run.',
      'capChunkReplayUnavailableNoWord':
          'Generate or attach Word sync before chunk replay.',
      'capChunkReplayUnavailable': 'Generate chunks from the active Word sync.',
      'capListeningAvailable': 'Document listening structure is ready.',
      'capListeningPredictedOnly':
          'Predicted or estimated cues only; not measured audio.',
      'capListeningUnavailableNoSubtitle':
          'Load subtitles before listening structure can run.',
      'capListeningUnavailableNoWord':
          'Needs Word sync before listening structure can be created.',
      'capListeningUnavailable':
          'No listening structure resource yet. Refresh or import a timeline resource.',
      'capPhoneEvidenceAvailable': 'Detailed phone evidence is ready.',
      'capPhoneEvidenceUnavailableNoSubtitle':
          'Load subtitles before phone evidence can run.',
      'capPhoneEvidenceUnavailable':
          'Run audio analysis or import a timeline with phone evidence.',
      'capTimelineResourceError':
          'Timeline refresh failed. Fix the issue, then refresh.',
      'frames': 'frames',
      'importLLTimeline': 'Import LLTimeline',
      'refresh': 'Refresh',
      'lltimelinePresent': 'LLTimeline present',
      'legacyTimelineFallback': 'Legacy timing fallback',
      'humanReviewed': 'Human reviewed',
      'productionReportReady': 'Production report ready',
      'productionReportMissing': 'Production report missing',
      'noTimelineCandidates': 'No Word sync candidates',
      'noPhoneTimelineCandidates': 'No Phone evidence candidates',
      'noChunkTimelineCandidates': 'No Chunk replay candidates',
      'activeTimelineLegacy': 'Word sync: legacy word timings',
      'activeTimelineGeneratedTiming': 'Word sync: generated word timings',
      'activePhoneTimelineMissing':
          'Phone evidence: unavailable until audio analysis runs',
      'activeChunkTimelineMissing': 'Chunk replay: unavailable until generated',
      'activeTimeline': 'Active timeline',
      'activateTimeline': 'Activate timeline',
      'generateChunks': 'Generate chunks',
      'manualReview': 'Manual review',
      'manualReviewQueued': 'Manual review entry is ready for Phase 2.3.',
    },
    'zh': {
      'settings': '设置',
      'moreActions': '更多操作',
      'playbackSettings': '播放设置',
      'general': '通用',
      'resourceSettings': '资源与转写',
      'externalToolsShort': '外部工具',
      'rate': '播放速度',
      'language': '界面语言',
      'system': '跟随系统',
      'english': 'English',
      'chinese': '简体中文',
      'japanese': '日本語',
      'learningLanguage': '学习语言',
      'l1Language': '母语（L1）',
      'l1LanguageHint': '仅用于从母语听觉习惯解释听力难点；不设置则保持中立诊断。',
      'l1NotSet': '未设置',
      'l1HintsTitle': '母语听觉视角',
      'l1UnsupportedPair': '当前语言组合暂无母语难点内容，仅显示基础诊断。',
      'l1ListenAgain': '复听',
      'l1SimilarClips': '同类片段',
      'l1SpecialtyPractice': '练习这句',
      'l1SpecialtyUnindexed': '尚未建立语料索引，仅显示当前媒体内的片段。',
      'l1SpecialtyEmpty': '你的材料里还没有同类片段。',
      'l1_difficulty_name_weak_function_words': '弱读功能词',
      'l1_difficulty_name_schwa_reduction': '元音弱化（schwa）',
      'l1_difficulty_name_final_consonants': '词尾辅音',
      'l1_difficulty_name_consonant_clusters': '辅音丛',
      'l1_difficulty_name_t_d_deletion': '词尾 t/d 脱落',
      'l1_difficulty_name_flapping': '弹舌音（flap）',
      'l1_difficulty_name_linking': '连读',
      'l1_difficulty_name_stress_timed_rhythm': '重音节奏压缩',
      'l1_difficulty_name_compressed_forms': '口语缩合形',
      'l1_difficulty_weak_function_words': '中文听觉习惯里每个音节都足量，英语夹在重音间的功能词可能几乎听不到。',
      'l1_difficulty_schwa_reduction': '中文元音不变质，英语弱读元音会缩成含糊的 ə，听起来像另一个词。',
      'l1_difficulty_final_consonants': '中文音节只以元音或 n/ng 结尾，词尾辅音容易被中文耳朵忽略。',
      'l1_difficulty_consonant_clusters': '中文没有辅音丛，连续辅音可能被听成多了个元音或少了个辅音。',
      'l1_difficulty_t_d_deletion': '连读中词尾 /t/ /d/ 常被弱化或省略，中文听觉没有补回它们的习惯。',
      'l1_difficulty_flapping': '美音把元音之间的 /t/ /d/ 读成快速弹舌，听感接近 /d/。',
      'l1_difficulty_linking': '中文音节边界清晰，英语把词尾辅音连进下一个元音，词边界会移动。',
      'l1_difficulty_stress_timed_rhythm': '英语为保持重音节拍会压缩非重读段，对中文节奏习惯来说快得抓不住。',
      'l1_difficulty_compressed_forms': 'gonna/wanna/didja 这类缩合要当作整体来认，不能逐词去听。',
      'subtitles': '字幕',
      'subtitlePreset': '字幕预设',
      'watching': '观影模式',
      'learning': '学习模式',
      'compact': '紧凑模式',
      'subtitleScale': '主字幕字号',
      'secondaryScale': '副字幕字号',
      'primaryFont': '主字幕字体',
      'secondaryFont': '副字幕字体',
      'systemFont': '系统字体',
      'serifFont': '衬线字体',
      'monospaceFont': '等宽字体',
      'horizontalPosition': '水平位置',
      'verticalPosition': '垂直位置',
      'resetSubtitlePosition': '重置字幕位置',
      'dragSubtitleHint': '拖动字幕可调整位置',
      'backgroundOpacity': '背景透明度',
      'transcriptWidth': '文稿宽度',
      'primaryColor': '主字幕颜色',
      'secondaryColor': '副字幕颜色',
      'externalTools': '可选外部工具',
      'close': '关闭',
      'save': '保存',
      'vocabulary': '词汇本',
      'listeningDictionary': '听力词典',
      'openListeningDictionary': '在词典中听例句',
      'dictionaryWord': '学习词条',
      'dictionaryPhrase': '学习短语',
      'dictionaryClips': '你的来源切片',
      'dictionaryCoverage': '你的语料里只有 {count} 条切片',
      'dictionaryNoClips': '还没有来源切片',
      'dictionaryNoClipsHint': '听字幕时打开“{word}”，即可保存第一条来源切片。',
      'dictionaryRevealSentence': '显示句子文本',
      'dictionaryClipReady': '可播放',
      'dictionaryClipNeedsSource': '需要定位来源文件',
      'dictionaryPlayClip': '播放来源切片',
      'dictionaryHeard': '这次听出来了',
      'dictionaryNotHeard': '这次没听出',
      'dictionaryMarkedHeard': '已标记：这次听出来了',
      'dictionaryMarkedNotHeard': '已标记：这次没听出',
      'dictionaryMarkUnavailable': '这条旧切片没有稳定句子关联，不能写入学习证据。',
      'dictionaryMarkFailed': '保存本次标记失败：{error}',
      'dictionaryLibrarySection': '媒体库中的更多例句',
      'dictionaryFindMore': '在我的媒体库中搜索',
      'dictionaryNoLibraryResults': '媒体库中暂时没有其他语境',
      'dictionaryCollect': '收为来源切片',
      'dictionaryCollected': '已收为该词条的来源切片',
      'dictionaryCollectFailed': '收藏切片失败：{error}',
      'corpusKindWord': '词',
      'corpusKindSentence': '句子',
      'corpusKindChunk': '语块',
      'dictionaryReindex': '重建媒体库语料索引',
      'dictionaryReindexDone': '已重建 {count} 条字幕轨的语料索引',
      'dictionaryReindexFailed': '重建语料索引失败：{error}',
      'dictionaryAddToReview': '加入复习',
      'dictionaryReviewQueued': '已加入声音复习',
      'dictionaryReviewFailed': '加入复习失败：{error}',
      'dictionaryReviewClip': '此切片加入复习',
      'huntingList': '猎词单',
      'huntingTargetCount': '正在攻克 {count} / 5 个目标',
      'huntingActiveTargets': '正在攻克',
      'huntingReviewCandidates': '复习反复失败候选',
      'huntingNoTargets': '还没有目标。可从词典详情把词或短语加入猎词单。',
      'huntingNoCandidates': '目前没有待确认的复习失败候选。',
      'huntingAdd': '加入',
      'huntingAdded': '已加入猎词单',
      'huntingAlreadyAdded': '已在猎词单中',
      'huntingArchived': '已移出正在攻克',
      'huntingUpdateFailed': '更新猎词单失败：{error}',
      'huntingArchive': '移出正在攻克',
      'huntingSourceManual': '从听力词典手动加入',
      'huntingSourceReview': '复习反复失败后确认加入',
      'huntingSourceInbox': '从 Listening Inbox 确认加入',
      'huntingFailureCount': '复习中失败 {count} 次',
      'huntingOpen': '打开猎词单',
      'huntingAddCurrent': '加入猎词单',
      'huntingStartMode': '开始狩猎模式',
      'huntingStopMode': '结束狩猎模式',
      'huntingStarted': '狩猎模式已就绪：当前媒体有 {count} 个出现点',
      'huntingStopped': '狩猎模式已结束',
      'huntingIndexNeeded': '当前媒体还没有语料索引；重建后才能定位目标。',
      'huntingListenFor': '留意听：“{target}”',
      'huntingDidYouHear': '刚才听出“{target}”了吗？',
      'huntingAnswerYes': '听出了',
      'huntingAnswerNo': '没听出',
      'huntingAnswerNotNoticed': '没注意',
      'huntingAnswerSaved': '狩猎作答已记录',
      'dictionarySortDefault': '默认顺序',
      'dictionarySortByRate': '按语速',
      'dictionaryWpm': '≈{wpm} 词/分',
      'dictionaryExternalHint': '库外参考（仅供参考，不作为练习素材）：',
      'dictionaryYouglish': '在 YouGlish 中打开',
      'dictionarySampledHint': '结果较多：已跨媒体采样，仅显示前 {count} 条',
      'dictionaryContentSection': '我的释义与笔记',
      'dictionarySenseFolders': '义项文件夹',
      'dictionarySenseFoldersHint': '这是可选的个人整理；来源切片不必归入任何义项。',
      'dictionaryNoSenseFolders': '还没有义项文件夹',
      'dictionaryAddSenseFolder': '新建义项文件夹',
      'dictionaryEditSenseFolder': '编辑义项文件夹',
      'dictionarySenseFolderLabel': '义项名称',
      'dictionarySenseFolderDefinition': '释义（可选）',
      'dictionarySenseFolderGloss': '简注（可选）',
      'dictionarySenseFolderExternalRef': '外部引用（可选）',
      'dictionarySenseFolderClipCount': '{count} 条切片',
      'dictionarySenseFolderEmpty': '尚未归入切片',
      'dictionaryUnassignedClips': '未归类切片',
      'dictionaryAssignSenseFolder': '归入义项',
      'dictionaryAssignedSenseFolder': '更改义项',
      'dictionaryUnassignSenseFolder': '从“{label}”移出',
      'dictionaryContentSaved': '释义与笔记已保存',
      'dictionaryUpdateFailed': '更新失败：{error}',
      'dictionaryUpgradeSuggestion': '来自 {count} 个语境的听力证据显示你可能已能听出它。',
      'home': '首页',
      'library': '内容库',
      'listenNow': '开始',
      'myLearning': '我的学习',
      'continueLearning': '继续学习',
      'continuePlayback': '继续播放',
      'noRecentMedia': '还没有最近媒体',
      'openMediaToContinue': '打开本地媒体后即可开始或继续听力。',
      'subtitleReadiness': '字幕状态',
      'notReadyYet': '未就绪',
      'savedWords': '已存词条',
      'localCore': '本地核心',
      'coreReady': '就绪',
      'startListening': '开始聆听',
      'learningTools': '学习资料',
      'contentActions': '内容',
      'subtitleActions': '字幕',
      'learningActions': '学习',
      'localSource': '本机视频或音频',
      'onlineSource': '打开支持的在线地址',
      'subtitleResourceSummary': '字幕与时间轴资源',
      'vocabularySummary': '听力过程中保存的词与短语',
      'review': '复习',
      'coachDashboard': '学习教练',
      'coachDashboardSummary': '诊断与下一步练习建议',
      'coachThisWeek': '最近 7 天听力证据',
      'coachNextSteps': '建议下一步',
      'coachNoSuggestions': '继续听和练习，积累证据后这里会出现建议。',
      'coachStarter': '建立第一批学习证据',
      'coachUnassessed': '尚未评估：暂无主动验证',
      'coachSuggestionReview': '复习到期声音卡',
      'coachSuggestionReviewReason': '已有到期复习计划',
      'coachSuggestionHunting': '确认反复听辨失败的词',
      'coachSuggestionHuntingReason': '复习失败产生了猎词候选',
      'coachSuggestionSpecialty': '回看 L1 听辨模式',
      'coachSuggestionSpecialtyReason': '已记录规则型难点提示；它不是音频确证',
      'coachSuggestionContinue': '继续真实内容输入',
      'coachSuggestionContinueReason': '近期泛听记录已形成可比较的基线',
      'coachStarter_complete_extensive_listening': '完成一次泛听',
      'coachStarter_complete_active_practice': '完成一次填空或听写',
      'coachStarter_review_due_items': '复习到期声音卡',
      'coachMetric_extensive_sessions': '泛听次数',
      'coachMetric_extensive_listening_ms': '泛听时长',
      'coachMetric_practice_attempts': '主动练习次数',
      'coachMetric_correct_practice_attempts': '练习正确次数',
      'coachMetric_review_attempts': '复习次数',
      'coachMetric_successful_review_attempts': '复习成功次数',
      'coachMetric_listening_capability_changes': '听力能力变化',
      'coachMetric_l1_difficulty_hits': 'L1 规则提示命中',
      'coachMaterials': '材料进展',
      'coachMaterialTrajectory': '理解度自报',
      'coachGraduate': '标记已毕业',
      'coachGraduateConfirmTitle': '将这份材料标记为已毕业？',
      'coachGraduateConfirmBody': '此操作只整理内容库，不会自动改变任何语言能力状态。',
      'coachEvidenceSource': '持久事实来源',
      'coachEvidenceCount': '周期内事实数',
      'coachEvidenceEmpty': '该周期内没有来源事实。',
      'coachReport_understood_all': '全部听懂',
      'coachReport_got_the_gist': '听懂大意',
      'coachReport_unclear': '仍不清楚',
      'coachReport_unknown': '未自报',
      'queueGraduated': '已毕业',
      'coachIntent_pin_intensive': '转入精听',
      'coachIntent_pin_extensive': '保留泛听',
      'coachMaterialAdjustTitle': '调整这份材料？',
      'coachMaterialAdjustBody': '该建议来自多次理解度自报；确认后只改变内容库队列。',
      'audioFirstReview': '声音优先的到期卡片',
      'noMediaSelected': '尚未选择媒体',
      'backToHome': '首页',
      'expandWorkbench': '展开',
      'openMedia': '打开媒体',
      'openUrl': '打开网址',
      'primarySubtitle': '主字幕',
      'secondarySubtitle': '副字幕',
      'noSecondarySubtitle': '无副字幕',
      'transcript': '字幕文稿',
      'wordLearning': '词汇学习',
      'diagnosis': '句子诊断',
      'practice': '测一下',
      'understandPosture': '听懂了吗？',
      'testPosture': '测一下？',
      'shadowPosture': '跟一下？',
      'shadowingPlannedTooltip': '跟读与录音会在 Phase 3.8 点亮。',
      'shadowingReadyTooltip': '跟读当前韵律语块，并与自己的录音做客观对比。',
      'shadowingPractice': '跟读模仿',
      'shadowingSpeed': '原音速度',
      'shadowingPlayOriginal': '播放原音',
      'shadowingStartRecording': '开始录音',
      'shadowingStopRecording': '停止并比较',
      'shadowingRecordAgain': '重新录音',
      'shadowingRecordingActive': '正在本地录音…原音已暂停。',
      'shadowingPermissionDenied': '麦克风权限已关闭，请在 macOS“隐私与安全性”中启用。',
      'openSystemSettings': '打开系统设置',
      'shadowingComparison': '客观对比 · 不评分',
      'shadowingPlayMine': '播放我的录音',
      'shadowingOriginal': '原音',
      'shadowingMine': '我的',
      'shadowingDurationDelta': '时长差',
      'shadowingSameDuration': '时长相同',
      'shadowingPauseCount': '停顿数 原音 / 我的',
      'shadowingPauseOffset': '平均停顿偏移',
      'selectWordFromTranscript': '在字幕文稿中点击单词后，可查看状态、释义和来源例句。',
      'diagnosisUnavailable': '暂无听感参照',
      'openSentenceDiagnosisHint': '载入字幕后，打开当前句即可查看词汇状态和听感参照。',
      'clozePractice': '挖空',
      'chunkDictation': '语块听写',
      'sentenceDictation': '整句听写',
      'practiceClozeTooltip': '挖掉一个已掌握词，用声音验证是否真的听出。',
      'practiceClozeUnavailable': '挖空需要词级时间轴。',
      'practiceChunkTooltip': '听当前语块并输入听到的内容。',
      'practiceChunkFallbackTooltip': '当前句没有可用语块，将回退到整句听写。',
      'practiceNeedsSentence': '打开一个字幕句后即可练习。',
      'practiceChoosePrompt': '为当前句选择挖空或听写。',
      'practiceWindow': '练习面板',
      'practiceProgress': '第 {current} / {total} 句',
      'practicePlayer': '当前句播放',
      'practicePlayerHint': '可复听、暂停或切换相邻句。',
      'hidePracticePlayer': '收起播放器',
      'showPracticePlayer': '显示播放器',
      'practiceEstimatedTiming': '当前时间轴为估算，复听窗口可能不够精确。',
      'practiceListenThenType': '先听音频，再输入你听到的内容。',
      'practiceHiddenText': '提交前答案不会显示。',
      'practiceAnswer': '你的答案',
      'createReviewOnFailure': '失败时存入复习',
      'submit': '提交',
      'replay': '复听',
      'retryPractice': '再练一次',
      'openDiagnosis': '加载参照',
      'saveToReview': '存入复习',
      'savedToReview': '已存复习',
      'practiceResult': '结果',
      'practiceCorrect': '正确',
      'practicePartial': '部分匹配',
      'practiceIncorrect': '还没听出',
      'practiceSkipped': '已跳过',
      'startExtensiveListening': '开始泛听',
      'finishExtensiveListening': '结束泛听',
      'listeningMode': '泛听',
      'extensiveListeningActive': '泛听进行中',
      'extensiveListeningIdle': '泛听未开始',
      'markListeningInbox': '标记到 Listening Inbox',
      'hardInterruptListening': '暂停查看',
      'listeningInbox': 'Listening Inbox',
      'listeningInboxEmpty': '还没有标记的泛听片段。',
      'comprehensionReportPrompt': '这次泛听理解得怎么样？',
      'huntingCompletionSummary': '狩猎：命中 {prompted} 次 / 听出 {recognized} 次',
      'skipReport': '跳过',
      'reportUnderstoodAll': '全懂',
      'reportGist': '大意懂了',
      'reportUnclear': '迷糊',
      'microIntensive': '微精听',
      'favoriteSegment': '收藏片段',
      'dismissInboxItem': '归档',
      'expected': '应为',
      'youTyped': '你写的是',
      'possibleWhy': '可能原因',
      'noWordSelected': '点击字幕单词以打开学习详情。',
      'dictionary': '词典',
      'noDictionary': '暂无词典结果',
      'userDefinition': '自定义释义',
      'personalNote': '个人笔记',
      'sources': '来源原句',
      'statusHistory': '状态历史',
      'currentStatus': '当前状态',
      'learningState': '学习状态',
      'meaningAndPronunciation': '释义与发音',
      'sourceSentences': '来源原句',
      'learningHistory': '学习记录',
      'noSourceSentences': '暂时没有记录来源原句。',
      'recordCurrentSentence': '记录当前句',
      'noLearningHistory': '暂时没有学习记录。',
      'earlier': '较早记录',
      'clear': '清除状态',
      'unknown_meaning': '不认识',
      'known_not_recognized': '认识但听不出',
      'known_recognized': '已掌握',
      'unassessed': '尚未评估',
      'not_acquired': '未掌握',
      'acquired': '已掌握',
      'capabilityReading': '阅读',
      'capabilityListening': '听力',
      'capabilitySpeaking': '口语',
      'capabilityWriting': '写作',
      'capabilityProfile': '能力画像',
      'listeningUpgradeSuggestion': '"{word}" 已在 {count} 个语境中听出，要标为听力已掌握吗？',
      'confirmListeningAcquired': '确认：已能听出',
      'deferUpgrade': '暂不升级',
      'apply': '应用',
      'heard': '本句：听出来了',
      'notHeard': '本句：没有听出',
      'importWordList': '导入已有词表',
      'importAssets': '导入词汇资产',
      'exportAssets': '导出词汇资产',
      'overwriteExisting': '覆盖已有状态',
      'previewImport': '导入预览',
      'import': '导入',
      'noWords': '该词汇本暂无词汇',
      'searchVocabulary': '搜索词汇',
      'vocabFilterAll': '全部',
      'vocabFilterCapabilityHint': '按能力通道筛选',
      'vocabularyBooks': '动态词汇本',
      'loopSentence': '循环当前句',
      'previousChunk': '上一语块',
      'nextChunk': '下一语块',
      'chunkMode': '语块',
      'loopChunk': '循环语块',
      'expandChunk': '展开语块',
      'subtitleMode': '字幕',
      'chunkReplayUnavailableControl': '当前句需要可用语块后才能复听。',
      'wordStyles': '词汇状态样式',
      'secondary': '副字幕',
      'secondarySubtitleUnavailable': '请先载入副字幕轨。',
      'noMediaControlsHint': '打开媒体后可使用播放控制',
      'taskSubtitleGeneration': '字幕生成',
      'taskAudioAnalysis': '音素证据分析',
      'taskStateWorking': '进行中',
      'taskStateSuccess': '已完成',
      'taskStateWarning': '需处理',
      'taskStateError': '失败',
      'taskStateCancelled': '已取消',
      'taskStateUnknown': '未知',
      'currentSentenceDiagnosis': '听感参照',
      'pronunciationProvider': '发音来源',
      'wordTimingSource': '词级时间来源',
      'pronunciationCache': '发音缓存',
      'cacheReusable': '可复用',
      'ready': '可用',
      'degraded': '降级',
      'providerUnavailable': '词典来源不可用',
      'noSourceSnapshot': '暂无来源原句',
      'encountered': '遇见',
      'times': '次',
      'openOnlineTitle': '使用 yt-dlp 打开在线媒体',
      'pageUrl': '页面网址',
      'addSource': '添加来源',
      'pasteSourceLink': '粘贴视频或音频链接',
      'recognizedSource': '识别到的来源',
      'youtubeSource': 'YouTube',
      'webSource': '网页地址',
      'playOnline': '在线播放',
      'downloadLocal': '下载到本机',
      'sourceAuthorizationNotice': '仅添加你有权访问的内容，并遵守来源平台的使用条款。',
      'invalidSourceUrl': '请输入有效的 http 或 https 地址。',
      'cancel': '取消',
      'resolvePlay': '解析并播放',
      'download': '下载',
      'downloadVideo': '下载视频',
      'downloadHere': '下载到此处',
      'startingDownload': '正在开始下载...',
      'downloadingVideo': '正在下载视频',
      'downloadComplete': '下载完成',
      'downloadFailed': '下载失败',
      'downloadCancelled': '下载已取消',
      'downloadingInBackground': '正在后台下载',
      'openDownloadedVideo': '打开已下载视频',
      'importEmbeddedText': '导入内嵌文本字幕',
      'usePrimary': '作为主字幕',
      'useSecondary': '作为副字幕',
      'exportLogs': '导出日志',
      'archiveMedia': '归档当前媒体',
      'openVideoAudio': '打开视频或音频',
      'importSubtitle': '导入字幕',
      'importSubtitleHint': '导入 SRT 或 WebVTT 字幕',
      'noTranscriptTitle': '还没有文稿',
      'backToCurrentSentence': '回到当前句',
      'subtitleResources': '字幕资源',
      'contentFit': '难度适配',
      'contentFitMeaning': '词汇',
      'contentFitSound': '语音',
      'fit_too_easy': '轻松',
      'fit_comprehensible': '合适',
      'fit_challenging': '有挑战',
      'fit_too_hard': '需要辅助',
      'contentFitIntensiveTarget': '你大概率看得懂，功夫在听辨上——适合精听的材料。',
      'contentFitInitialEstimate': '初始估计',
      'contentFitCalibrated': '已按你的使用校准',
      'contentFitLowProfile': '词汇画像对这段材料的覆盖还很少，这是保守估计——先标注一些词会更准。',
      'coldStartQuickMarking': '快速标注',
      'coldStartEmpty': '目前没有需要标注的高频词。',
      'coldStartProgress': '{current} / {total}',
      'coldStartKnownRecognized': '认识也听得出',
      'coldStartKnownNotRecognized': '看得懂听不出',
      'coldStartUnknownMeaning': '不认识',
      'coldStartSkip': '跳过',
      'mediaLibrary': '媒体库',
      'mediaLibraryEmpty': '打开过的媒体会出现在这里。',
      'queueIntensive': '精听靶单',
      'queueExtensive': '泛听队列',
      'queueDeferred': '暂缓区',
      'queueUnsorted': '未分级',
      'goldenTargetBadge': '精听靶',
      'familiarRelistenBadge': '熟料回听',
      'startExtensiveAction': '泛听',
      'startIntensiveAction': '精听',
      'pinExtensiveAction': '固定到泛听队列',
      'pinIntensiveAction': '固定到精听靶单',
      'deferMediaAction': '暂缓',
      'clearTriageAction': '清除固定 / 暂缓',
      'familiarSuggestionsToggle': '建议回听熟悉材料',
      'mediaFileMissing': '文件已不存在',
      'contentFitWhy': '依据',
      'contentFitDecisive': '影响档位',
      'fit_signal_unknown_meaning_density': '生词密度',
      'fit_signal_unassessed_density': '未标注词比例',
      'fit_signal_known_not_recognized_density': '看得懂听不出的词',
      'fit_signal_speech_rate_wpm': '语速',
      'fit_signal_weak_form_density': '弱读密度',
      'fit_signal_compression_density': '压缩密度',
      'fit_signal_mean_chunk_length': '平均意群长度',
      'fit_signal_comprehension_report_unclear_ratio': '你自报"没听懂"的比例',
      'fit_signal_practice_correct_rate': '你的练习正确率',
      'noSubtitleResources': '暂无字幕资源',
      'activeSubtitle': '当前字幕',
      'activateSubtitle': '激活字幕',
      'sentenceTiming': '句级',
      'wordTiming': '词级',
      'chunkTiming': '分块',
      'phoneTiming': '音素',
      'resourcePartial': '部分可用',
      'resourceLearningCapabilities': '学习能力',
      'resourceReady': '可以使用',
      'resourceArchived': '已归档',
      'technicalDetails': '技术详情',
      'resourceTimelineDetailsBelow': '详情见下方',
      'resourceActivateToInspect': '激活后检查',
      'diagnosisSummary': '诊断摘要',
      'diagnosisEvidence': '证据与分析',
      'diagnosisNoConclusion': '暂未发现明确的听辨障碍。',
      'resourceActions': '资源操作',
      'archiveResource': '归档资源',
      'restoreResource': '恢复资源',
      'deleteResource': '删除资源',
      'exportSubtitle': '导出字幕',
      'exportSubtitleFormat': '选择导出字幕格式',
      'exportLLTimelineJson': '导出 LLTimeline JSON',
      'deleteSubtitleResourceBody': '从本地资源库删除这个字幕资源及其关联时间轴？',
      'cues': '句',
      'timelineFingerprintMismatch': '时间轴媒体不匹配',
      'timelineFingerprintMismatchBody':
          '这个 LLTimeline 资源来自不同的媒体 fingerprint。只有在你确认它匹配当前媒体时才应挂载。',
      'attachAnyway': '仍然挂载',
      'previousSentence': '上一句',
      'nextSentence': '下一句',
      'restartMedia': '重新播放媒体',
      'playPause': '播放 / 暂停',
      'stop': '停止',
      'stopSourceLoop': '停止循环',
      'loopRange': '范围循环',
      'loopReview': '复查循环',
      'loopPractice': '练习循环',
      'loopInbox': '收件箱循环',
      'loopRhythm': '节奏循环',
      'loopPhone': '音素循环',
      'loopHotspot': '热点循环',
      'slicePlayback': '来源切片',
      'slicePlaybackAudioFirst': '音频优先的来源切片',
      'slicePlaybackInvalidRange': '这个来源切片的时间范围无效',
      'slicePlaybackNoSentence': '没有可用的来源原句快照。',
      'slicePlaybackSourceMedia': '来源媒体',
      'slicePlaybackReplay': '重新播放切片',
      'slicePlaybackPause': '暂停',
      'slicePlaybackPlay': '播放',
      'slicePlaybackLooping': '循环切片',
      'slicePlaybackPlayOnce': '播放一次',
      'slicePlaybackShowVideo': '显示视频',
      'slicePlaybackHideVideo': '隐藏视频',
      'compactMediaPane': '压缩视频区',
      'resetWorkbenchLayout': '重置媒体/文稿比例',
      'audioTrack': '音轨',
      'embeddedSubtitles': '内嵌字幕',
      'primaryOffset': '主字幕偏移',
      'secondaryOffset': '副字幕偏移',
      'generateSubtitles': '生成字幕',
      'generateWholeMedia': '生成完整媒体字幕',
      'primarySubtitleGenerationStarted': '字幕生成已开始。任务完成后会自动载入为主字幕。',
      'secondarySubtitleGenerationStarted': '字幕生成已开始。任务完成后会自动载入为副字幕。',
      'loadingGeneratedPrimarySubtitle': '正在载入生成的主字幕...',
      'generatedPrimarySubtitleLoaded': '已载入生成的主字幕',
      'generatedSecondarySubtitleLoaded': '已载入生成的副字幕',
      'generatedSubtitleResourceWarning': '部分学习资源需要处理',
      'generatePrimaryHint': '完成后可作为主字幕载入。',
      'generateSecondaryHint': '完成后可作为副字幕载入。',
      'transcriptionCenter': 'ASR 模型与任务',
      'models': '模型',
      'model': '模型',
      'jobs': '任务',
      'modelRequired': '需要转录模型',
      'installModelFirst': '请先在 ASR 模型与任务中安装或注册兼容模型。',
      'transcriptionLanguage': '识别语言',
      'automatic': '自动检测',
      'translateEnglish': '翻译为英文',
      'multilingual': '多语言',
      'registerCustomModel': '注册自定义模型',
      'install': '安装',
      'syntaxCapabilityTitle': '本地句法增强',
      'syntaxCapabilityDescription': '可选的本地语法分析可增强部分语流与语义分组提示。播放和字幕始终不依赖此能力。',
      'syntaxCoreUnavailable': '本地核心不可用',
      'syntaxCancel': '取消',
      'syntaxVerify': '校验',
      'syntaxUpdate': '更新',
      'syntaxDisable': '停用',
      'syntaxEnable': '启用',
      'syntaxUninstall': '卸载',
      'syntaxRebuild': '重建',
      'syntaxTrackBackground': '当前字幕轨道会在后台安静分析。',
      'syntaxCacheReused': '已复用缓存',
      'syntaxSentences': '句',
      'syntaxNotInstalled': '未安装',
      'syntaxDownloading': '正在下载',
      'syntaxReady': '可用',
      'syntaxPartial': '部分可用',
      'syntaxFailed': '失败',
      'syntaxStale': '需要更新',
      'syntaxDisabled': '已停用',
      'remove': '删除',
      'archive': '归档',
      'retry': '重试',
      'noTranscriptionJobs': '暂无转录任务',
      'loadGeneratedSubtitle': '载入生成字幕',
      'transcriptionDefaults': '转录默认设置',
      'phoneticAnalysis': '实验性音频检测',
      'phoneticAnalysisCenter': '音频分析模型与任务',
      'experimental': '实验性',
      'llmProviders': 'AI 服务',
      'llmProvidersDescription':
          '厂商中立的 LLM 服务，用于可选的语义反馈。你可以选择自己的云端或本地模型；没有它核心学习照常可用。',
      'llmDataWarning': '你判定的文本（转写与字幕）会发送到你配置的服务地址。自定义地址的数据处理方式由该服务器决定。',
      'llmNotQualified': '未获显示资格：此处任何判定仅供诊断，未经独立资格评估前不会作为学习反馈出现。',
      'llmNoProviders': '尚未配置任何服务。',
      'llmAddProvider': '添加服务',
      'llmAdapterKind': '协议',
      'llmDisplayName': '名称',
      'llmBaseUrl': '服务地址',
      'llmModelId': '模型',
      'llmApiKey': 'API 密钥（只写）',
      'llmApiKeyHint': '由后端保存到系统钥匙串，不再回显。',
      'llmAllowedUses': '允许用途',
      'llmUseJudgment': '语义判定',
      'llmUseRubric': '评分尺生成',
      'llmRegister': '保存服务',
      'llmTest': '测试',
      'llmRemove': '删除',
      'llmKeyStored': '已存密钥',
      'llmProbing': '测试中…',
      'llmProbeSupported': '结构化输出：支持',
      'llmProbeUnsupported': '结构化输出：不支持',
      'llmProbeFailed': '测试失败',
      'llmSidecarUnavailable': '连接后端后可管理 AI 服务。',
      'applicationVerified': '已通过应用验证',
      'notApplicationVerified': '未通过应用验证',
      'distributionAllowed': '允许分发',
      'distributionNotAllowed': '不允许分发',
      'noPhoneticAnalysisJobs': '暂无音频分析任务',
      'clearCompleted': '清除已完成',
      'deleteJob': '删除',
      'jobCompleted': '已完成',
      'jobFailed': '失败',
      'jobCancelled': '已取消',
      'jobInterrupted': '已中断',
      'jobQueued': '排队中',
      'jobExtracting': '提取音频中',
      'jobRecognizingPhones': '识别音素中',
      'jobAligning': '对齐中',
      'jobAnalyzing': '分析中',
      'confirmClearJobs': '清除所有已完成、失败和已取消的任务？',
      'confirmDeleteJob': '删除此任务？',
      'phoneticAnalysisPreference': '分析偏好',
      'phoneticOnDemand': '按需分析',
      'phoneticBatch': '批量分析',
      'disabled': '禁用',
      'phonemeRibbonVisible': '显示文字线音素带',
      'soundPatternRibbonVisible': '显示听感参照',
      'soundPatternDisplayMode': '听感参照',
      'rhythmReferenceCitation': 'A · 字典读音',
      'rhythmReferenceConnected': 'B · 预测可听结构',
      'rhythmReferenceActual': 'C · 实际可听结构',
      'rhythmReferenceCitationTooltip': 'A · 来自字典的读音与词汇重音',
      'rhythmReferenceConnectedTooltip': 'B · 词典词界在连续语流中可能如何重组',
      'rhythmReferenceActualTooltip': 'C · 当前音频中由音素、时间和韵律支持的实际可听分组',
      'showFullSoundStructure': '展开完整句结构',
      'collapseSoundStructure': '收起并跟随当前位置',
      'connectedSpeechReference': '预测可听结构',
      'connectedSpeechReferenceTooltip': 'A → B：对比书写词界与语言规则预测的可听音组。',
      'connectedSpeechUnavailable': '当前句没有预测到可听结构变化',
      'citationPronunciationUnavailable': '当前句暂无字典读音',
      'showPhoneEvidence': '查看音素证据',
      'hidePhoneEvidence': '收起音素证据',
      'phonemeRibbonStyle': '音素带显示方式',
      'phonemeRibbonWindow': '滑动窗口',
      'phonemeRibbonWave': '波浪放大',
      'textPhonemeRibbonHint': '文字线：来自字幕单词的稳定教学音素。',
      'soundPatternRibbonHint': '听感层：默认显示听感结构，音素证据作为细节。',
      'soundPatternUnavailable': '当前句暂无音素证据',
      'soundPatternUnavailableTooltip': '音素证据需要当前句已有音频分析，或导入的时间轴资源提供对应证据。',
      'rhythmFrameUnavailable': '当前句暂无听感结构',
      'rhythmRibbonHint': '可听结构：抓住当前音频里能听到的信息锚点，微弱的弱读音团退到背景路径。',
      'expectedPronunciationReference': '预期',
      'expectedPronunciationTooltip': '当前句的词典发音参考。',
      'soundReferenceNoData': '暂无本次音频的听感数据',
      'loadCurrentSentence': '加载当前句',
      'loadWholeTrack': '加载全部字幕',
      'soundReferenceLoadHint': '加载当前句较快；加载全部字幕后切换句子无需等待。',
      'canonicalPronunciation': '规范发音',
      'rulePrediction': '规则预测',
      'audioDetectionExperimental': '音频检测（实验性）',
      'listeningRhythm': '听感结构',
      'listeningPredictedBadge': '预测',
      'listeningPredictedTooltip': '基于文本预测，非本段音频实测。听感结构需有词级时长、能量或音高证据才算音频支持。',
      'stressAnchors': '可听信息锚点',
      'weakGroups': '弱读音团',
      'compressedSpans': '压缩区',
      'listeningHotspots': '听感热点',
      'rhythmQuality': '节奏置信度',
      'currentDetectedPhone': '当前检测音素',
      'loopEvidence': '循环播放证据',
      'feedbackConfirmed': '符合听感',
      'feedbackRejected': '不准确',
      'feedbackIgnored': '忽略',
      'preferredQuality': '首选质量',
      'defaultDestination': '默认字幕目标',
      'exportSrt': '导出 SRT',
      'regenerate': '使用当前算法重新生成',
      'runtimeReady': '运行时已就绪',
      'learningAssets': '学习资产',
      'resources': '离线学习数据',
      'words': '单词',
      'phones': '音素',
      'chunks': '语块',
      'phrases': '短语',
      'word': '单词',
      'phrase': '短语',
      'phraseCandidates': '短语候选',
      'phraseCandidatesHint': '查看当前字幕句中的固定搭配。只有手动保存的短语才会成为学习资产。',
      'noPhraseCandidates': '当前句没有可用的短语候选。',
      'confirmPhrase': '保存短语',
      'openSubtitles': '搜索 OpenSubtitles',
      'openSubtitlesApiKey': 'OpenSubtitles API Key',
      'openMediaForSubtitles': '请先打开媒体，再搜索字幕。',
      'configureOpenSubtitlesNow': '请输入 OpenSubtitles API Key 以继续。',
      'search': '搜索',
      'title': '标题',
      'filename': '文件名',
      'mediaHash': '媒体哈希',
      'lemmaCorrectionSaved': 'Lemma 修正已保存',
      'configureOpenSubtitles': '请先在设置中配置 OpenSubtitles API Key',
      'pronunciation': '播放发音',
      'pronunciationUnavailable': '发音音频暂时不可用。',
      'highlightCurrentWord': '高亮当前词',
      'groupingMode': '分组',
      'groupingModeHint': '统一字幕的分组显示方式。',
      'groupingModeOff': '关',
      'groupingModeProsodic': '语流分组',
      'groupingModeSemantic': '语义分组',
      'groupingModeCompare': '对比',
      'senseGroupDataAvailable': '可用',
      'senseGroupDataNotReady': '数据未就绪',
      'senseGroupDataNotReadyHint': '语义分组数据未就绪；字幕将回退为逐词显示',
      'groupingSemanticProvisional': '临时标记（启发式）',
      'groupingDivergenceHint': '语义与语流在此不一致',
      'chunkDisplayStyle': '分组显示方式',
      'chunkDisplayCapsule': '胶囊分组',
      'chunkDisplaySpacing': '仅间距分组',
      'highlightCurrentChunk': '高亮当前分组',
      'chunkHighlightStyle': '当前分组提示方式',
      'chunkHighlightBackground': '静态背景',
      'chunkHighlightBounce': '慢速缩放跳动',
      'chunkHighlightGlow': '慢速发光',
      'wordHighlightStyle': '当前词跳动方式',
      'wordHighlightBackground': '背景高亮',
      'wordHighlightBounce': '放大跳动',
      'wordHighlightGlow': '发光',
      'wordHighlightIntensity': '当前词高亮强度',
      'ruleHints': '语流规则提示',
      'ruleHintsOff': '关闭',
      'ruleHintsLikely': '仅高可能性',
      'ruleHintsAll': '全部',
      'rulePredictionDisclaimer': '以下是规则预测，并非真实音频检测：',
      'diagnosis_meaning_barrier': '不认识的词汇可能阻碍理解。',
      'diagnosis_recognition_barrier': '已认识的词汇在本句中没有被听出。',
      'diagnosis_insufficient_information': '请先判断剩余词汇，再形成结论。',
      'diagnosis_other_factors': '词汇状态不能完全解释当前听力困难。',
      'characters': '字',
      'possibleListeningFactors': '可能涉及的听辨因素（非检测结果）：',
      'diagnosis_reason_tone_confusion': '声调混淆',
      'diagnosis_reason_word_boundary': '词边界切分',
      'diagnosis_reason_homophone': '同音词',
      'diagnosis_reason_neutral_tone': '轻声',
      'diagnosis_reason_tone_sandhi': '变调',
      'diagnosis_reason_weak_form': '弱读',
      'diagnosis_reason_linking': '连读',
      'diagnosis_reason_elision': '省音',
      'diagnosis_reason_assimilation': '同化',
      'diagnosis_reason_fuzzy_boundary': '边界模糊',
      'diagnosis_reason_reduced_form': '弱化形式',
      'timelineResource': '时间轴资源',
      'capabilityReadiness': '学习能力',
      'capabilityStateAvailable': '可用',
      'capabilityStateGenerating': '生成中',
      'capabilityStateDegraded': '降级',
      'capabilityStateUnavailable': '不可用',
      'capabilityStateUnsupported': '不支持',
      'capabilityStateStale': '可能过期',
      'capabilityStateError': '错误',
      'capabilitySubtitles': '字幕',
      'capabilityWordSync': '单词同步',
      'capabilityChunkReplay': '语块复听',
      'capabilityListeningStructure': '听感结构',
      'capabilityPhoneEvidence': '音素证据',
      'capSubtitlesAvailable': '已加载当前字幕轨。',
      'capSubtitlesArchived': '当前字幕已归档。',
      'capSubtitlesUnavailable': '请导入、生成、搜索、提取或挂载字幕。',
      'capWordSyncAvailable': '当前字幕已有词级时间。',
      'capWordSyncEstimated': '词级时间为估计值，高亮可能不精确。',
      'capWordSyncUnavailableNoSubtitle': '需要先加载字幕，才能进行单词同步。',
      'capWordSyncUnavailable': '需要可用的单词同步时间轴或生成的词级时间。',
      'capWordSyncGeneratedTimings': '已加载生成的词级时间。',
      'capChunkReplayAvailable': '语块复听已就绪。',
      'capChunkReplayUnavailableNoSubtitle': '需要先加载字幕，才能进行语块复听。',
      'capChunkReplayUnavailableNoWord': '需要先生成或挂载单词同步。',
      'capChunkReplayUnavailable': '可从当前单词同步生成语块。',
      'capListeningAvailable': '文档级听感结构已就绪。',
      'capListeningPredictedOnly': '仅有预测或估计提示，不是实测音频结论。',
      'capListeningUnavailableNoSubtitle': '需要先加载字幕，才能生成听感结构。',
      'capListeningUnavailableNoWord': '需要单词同步后，才能创建听感结构。',
      'capListeningUnavailable': '暂无听感结构资源。请刷新或导入时间轴资源。',
      'capPhoneEvidenceAvailable': '详细音素证据已就绪。',
      'capPhoneEvidenceUnavailableNoSubtitle': '需要先加载字幕，才能查看音素证据。',
      'capPhoneEvidenceUnavailable': '请运行音频分析，或导入包含音素证据的时间轴。',
      'capTimelineResourceError': '时间轴刷新失败。修复问题后请刷新。',
      'frames': '帧',
      'importLLTimeline': '导入 LLTimeline',
      'refresh': '刷新',
      'lltimelinePresent': '已导入 LLTimeline',
      'legacyTimelineFallback': '旧时间轴降级',
      'humanReviewed': '人工复核',
      'productionReportReady': '生产报告已就绪',
      'productionReportMissing': '暂无生产报告',
      'noTimelineCandidates': '暂无单词同步候选',
      'noPhoneTimelineCandidates': '暂无音素证据候选',
      'noChunkTimelineCandidates': '暂无语块复听候选',
      'activeTimelineLegacy': '单词同步：旧词级时间',
      'activeTimelineGeneratedTiming': '单词同步：已生成词级时间',
      'activePhoneTimelineMissing': '音素证据：需要先运行音频分析',
      'activeChunkTimelineMissing': '语块复听：需要先生成语块',
      'activeTimeline': '当前时间轴',
      'activateTimeline': '激活时间轴',
      'generateChunks': '生成语块',
      'manualReview': '人工复核',
      'manualReviewQueued': '人工复核入口已就绪，完整编辑器将在 Phase 2.3 推进。',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (value) => value.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
