import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

final appLanguage = ValueNotifier<String>('system');

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('zh')];

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations) ??
      AppLocalizations(
        Localizations.maybeLocaleOf(context) ?? const Locale('en'),
      );

  String text(String key) =>
      (_values[locale.languageCode] ?? _values['en']!)[key] ??
      _values['en']![key] ??
      key;

  String status(String? value) => text(value ?? 'clear');
  String diagnosis(String kind) => text('diagnosis_$kind');

  /// Localized label for a per-language diagnosis reason (e.g. `tone_confusion`).
  /// Unknown reasons degrade to their raw name so a new language's reason never
  /// breaks rendering.
  String diagnosisReason(String name) {
    final key = 'diagnosis_reason_$name';
    final localized = text(key);
    return localized == key ? name : localized;
  }

  static const delegate = _AppLocalizationsDelegate();

  static const _values = <String, Map<String, String>>{
    'en': {
      'settings': 'Settings',
      'moreActions': 'More actions',
      'playbackSettings': 'Playback settings',
      'general': 'General',
      'resourceSettings': 'Resources',
      'externalToolsShort': 'External tools',
      'rate': 'Playback speed',
      'language': 'Language',
      'system': 'Follow system',
      'english': 'English',
      'chinese': '简体中文',
      'japanese': '日本語',
      'learningLanguage': 'Learning language',
      'subtitles': 'Subtitles',
      'subtitlePreset': 'Subtitle preset',
      'watching': 'Watching',
      'learning': 'Learning',
      'compact': 'Compact',
      'subtitleScale': 'Primary font size',
      'secondaryScale': 'Secondary font size',
      'primaryFont': 'Primary font',
      'secondaryFont': 'Secondary font',
      'systemFont': 'System font',
      'serifFont': 'Serif',
      'monospaceFont': 'Monospace',
      'horizontalPosition': 'Horizontal position',
      'verticalPosition': 'Vertical position',
      'resetSubtitlePosition': 'Reset subtitle position',
      'dragSubtitleHint': 'Drag the subtitle to move it',
      'backgroundOpacity': 'Background opacity',
      'transcriptWidth': 'Transcript width',
      'primaryColor': 'Primary color',
      'secondaryColor': 'Secondary color',
      'externalTools': 'Optional external tools',
      'close': 'Close',
      'save': 'Save',
      'vocabulary': 'Vocabulary',
      'home': 'Home',
      'library': 'Library',
      'listenNow': 'Listen',
      'myLearning': 'My learning',
      'continueLearning': 'Continue learning',
      'continuePlayback': 'Continue',
      'noRecentMedia': 'No recent media yet',
      'openMediaToContinue': 'Open local media to start or resume listening.',
      'subtitleReadiness': 'Subtitles',
      'notReadyYet': 'Not ready',
      'savedWords': 'Saved words',
      'localCore': 'Local core',
      'coreReady': 'Ready',
      'startListening': 'Start listening',
      'learningTools': 'Learning tools',
      'contentActions': 'Content',
      'subtitleActions': 'Subtitles',
      'learningActions': 'Learning',
      'localSource': 'Video or audio from this Mac',
      'onlineSource': 'Open a supported online address',
      'subtitleResourceSummary': 'Subtitles and timeline resources',
      'vocabularySummary': 'Words and phrases saved while listening',
      'review': 'Review',
      'audioFirstReview': 'Audio-first due cards',
      'noMediaSelected': 'No media selected',
      'openMedia': 'Open media',
      'openUrl': 'Open URL',
      'primarySubtitle': 'Primary subtitle',
      'secondarySubtitle': 'Secondary subtitle',
      'noSecondarySubtitle': 'No secondary subtitle',
      'transcript': 'Transcript',
      'wordLearning': 'Word learning',
      'diagnosis': 'Diagnosis',
      'practice': 'Practice',
      'understandPosture': 'Understand?',
      'testPosture': 'Test?',
      'shadowPosture': 'Shadow?',
      'shadowingPlannedTooltip': 'Shadowing and recording arrive in Phase 3.8.',
      'selectWordFromTranscript':
          'Select a word in the transcript to see status, meaning, and source examples.',
      'diagnosisUnavailable': 'No listening reference yet',
      'openSentenceDiagnosisHint':
          'Load subtitles, then open a sentence to see vocabulary status and sound references.',
      'clozePractice': 'Cloze',
      'chunkDictation': 'Chunk dictation',
      'sentenceDictation': 'Sentence dictation',
      'practiceClozeTooltip': 'Blank a known word and verify it by ear.',
      'practiceClozeUnavailable': 'Cloze needs word-level timing.',
      'practiceChunkTooltip': 'Type the current chunk from audio.',
      'practiceChunkFallbackTooltip':
          'No active chunk here; this falls back to the sentence.',
      'practiceNeedsSentence': 'Open a subtitle sentence to practice.',
      'practiceChoosePrompt': 'Choose cloze or dictation for this sentence.',
      'markStuckPoint': 'Mark stuck',
      'skipStuckPoint': 'Skip',
      'practiceEstimatedTiming':
          'Timing is estimated; the replay window may be approximate.',
      'practiceListenThenType': 'Listen, then type what you heard.',
      'practiceHiddenText': 'The answer stays hidden until you submit.',
      'practiceAnswer': 'Answer',
      'createReviewOnFailure': 'Save a failed attempt to review',
      'submit': 'Submit',
      'replay': 'Replay',
      'retryPractice': 'Try again',
      'openDiagnosis': 'Load reference',
      'saveToReview': 'Save to review',
      'savedToReview': 'Saved to review',
      'practiceResult': 'Result',
      'practiceCorrect': 'correct',
      'practicePartial': 'partly matched',
      'practiceIncorrect': 'not yet',
      'practiceSkipped': 'skipped',
      'sessionSummary': 'Session summary',
      'finishIntensive': 'Finish intensive',
      'intensiveFinished': 'Finished',
      'finishIntensiveWithOpen':
          'There are {count} open stuck points. Finish anyway?',
      'startExtensiveListening': 'Start extensive listening',
      'finishExtensiveListening': 'Finish extensive listening',
      'listeningMode': 'Listening',
      'extensiveListeningActive': 'Extensive listening is active',
      'extensiveListeningIdle': 'Extensive listening is idle',
      'markListeningInbox': 'Mark Listening Inbox',
      'hardInterruptListening': 'Pause and inspect',
      'listeningInbox': 'Listening Inbox',
      'listeningInboxEmpty': 'No marked listening moments yet.',
      'comprehensionReportPrompt': 'How much did this session make sense?',
      'skipReport': 'Skip',
      'reportUnderstoodAll': 'All clear',
      'reportGist': 'Got the gist',
      'reportUnclear': 'Unclear',
      'microIntensive': 'Micro intensive',
      'favoriteSegment': 'Favorite segment',
      'dismissInboxItem': 'Archive',
      'summaryStuck': 'Stuck',
      'summaryResolved': 'Solved',
      'summaryVerified': 'Verified',
      'summaryReview': 'Review',
      'summaryUnexplained': 'Unexplained',
      'openStuckPoints': 'Open issues',
      'closeStuckPoint': 'Close',
      'familiarMaterialMarked': 'Marked as familiar listening material.',
      'expected': 'Expected',
      'youTyped': 'You typed',
      'possibleWhy': 'Possible reason',
      'noWordSelected': 'Click a subtitle word to open its learning details.',
      'dictionary': 'Dictionary',
      'noDictionary': 'No dictionary result',
      'userDefinition': 'Your definition',
      'personalNote': 'Personal note',
      'sources': 'Sources',
      'statusHistory': 'Status history',
      'currentStatus': 'Current status',
      'learningState': 'Learning state',
      'meaningAndPronunciation': 'Meaning and pronunciation',
      'sourceSentences': 'Source sentences',
      'learningHistory': 'Learning history',
      'noSourceSentences': 'No source sentence recorded yet.',
      'recordCurrentSentence': 'Record current',
      'noLearningHistory': 'No learning history yet.',
      'earlier': 'Earlier',
      'clear': 'Clear',
      'unknown_meaning': 'Unknown meaning',
      'known_not_recognized': 'Known, not recognized',
      'known_recognized': 'Known and recognized',
      'unassessed': 'Not yet assessed',
      'not_acquired': 'Not acquired',
      'acquired': 'Acquired',
      'capabilityReading': 'Reading',
      'capabilityListening': 'Listening',
      'capabilitySpeaking': 'Speaking',
      'capabilityWriting': 'Writing',
      'capabilityProfile': 'Capability profile',
      'listeningUpgradeSuggestion': '"{word}" heard in {count} contexts — mark listening as acquired?',
      'confirmListeningAcquired': 'Confirm: can hear it',
      'deferUpgrade': 'Not yet',
      'apply': 'Apply',
      'heard': 'This sentence: heard',
      'notHeard': 'This sentence: not heard',
      'importWordList': 'Import word list',
      'importAssets': 'Import vocabulary assets',
      'exportAssets': 'Export vocabulary assets',
      'overwriteExisting': 'Overwrite existing classified words',
      'previewImport': 'Import preview',
      'import': 'Import',
      'noWords': 'No words in this book',
      'searchVocabulary': 'Search vocabulary',
      'vocabularyBooks': 'Vocabulary books',
      'loopSentence': 'Loop sentence',
      'previousChunk': 'Previous chunk',
      'nextChunk': 'Next chunk',
      'chunkMode': 'Chunks',
      'loopChunk': 'Loop chunk',
      'expandChunk': 'Expand chunk',
      'subtitleMode': 'Subtitle',
      'chunkReplayUnavailableControl':
          'Chunk replay needs an active chunk for the current sentence.',
      'wordStyles': 'Word styles',
      'secondary': 'Secondary',
      'secondarySubtitleUnavailable': 'Load a secondary subtitle track first.',
      'noMediaControlsHint': 'Open media to enable playback controls',
      'taskSubtitleGeneration': 'Subtitle generation',
      'taskAudioAnalysis': 'Phone evidence analysis',
      'taskStateWorking': 'Working',
      'taskStateSuccess': 'Done',
      'taskStateWarning': 'Needs attention',
      'taskStateError': 'Failed',
      'taskStateCancelled': 'Cancelled',
      'taskStateUnknown': 'Unknown',
      'currentSentenceDiagnosis': 'Listening reference',
      'pronunciationProvider': 'Pronunciation provider',
      'wordTimingSource': 'Word timing source',
      'pronunciationCache': 'Pronunciation cache',
      'cacheReusable': 'reusable',
      'ready': 'ready',
      'degraded': 'degraded',
      'providerUnavailable': 'Provider unavailable',
      'noSourceSnapshot': 'No source snapshot',
      'encountered': 'encountered',
      'times': 'times',
      'openOnlineTitle': 'Open online media with yt-dlp',
      'pageUrl': 'Page URL',
      'addSource': 'Add source',
      'pasteSourceLink': 'Paste a video or audio link',
      'recognizedSource': 'Recognized source',
      'youtubeSource': 'YouTube',
      'webSource': 'Web address',
      'playOnline': 'Play online',
      'downloadLocal': 'Download to this Mac',
      'sourceAuthorizationNotice':
          'Only add content you are authorized to access. Provider terms still apply.',
      'invalidSourceUrl': 'Enter a valid http or https address.',
      'cancel': 'Cancel',
      'resolvePlay': 'Resolve and play',
      'download': 'Download',
      'downloadVideo': 'Download video',
      'downloadHere': 'Download here',
      'startingDownload': 'Starting download...',
      'downloadingVideo': 'Downloading video',
      'downloadComplete': 'Download complete',
      'downloadFailed': 'Download failed',
      'downloadCancelled': 'Download cancelled',
      'downloadingInBackground': 'Downloading in background',
      'openDownloadedVideo': 'Open downloaded video',
      'importEmbeddedText': 'Import embedded text subtitle',
      'usePrimary': 'Use as primary',
      'useSecondary': 'Use as secondary',
      'exportLogs': 'Export logs',
      'archiveMedia': 'Archive current media',
      'openVideoAudio': 'Open video or audio',
      'importSubtitle': 'Import subtitle',
      'importSubtitleHint': 'Import SRT or WebVTT subtitles',
      'noTranscriptTitle': 'No transcript yet',
      'backToCurrentSentence': 'Back to current',
      'subtitleResources': 'Subtitle resources',
      'contentFit': 'Difficulty',
      'contentFitMeaning': 'Vocabulary',
      'contentFitSound': 'Sound',
      'fit_too_easy': 'Easy',
      'fit_comprehensible': 'Comfortable',
      'fit_challenging': 'Challenging',
      'fit_too_hard': 'Demanding',
      'contentFitIntensiveTarget':
          'You can likely follow the text, but decoding by ear will be the work — good intensive listening material.',
      'contentFitInitialEstimate': 'Initial estimate',
      'contentFitCalibrated': 'Calibrated by your usage',
      'contentFitLowProfile':
          'Your vocabulary profile covers little of this transcript yet, so this is a conservative guess. Marking a few words will sharpen it.',
      'coldStartQuickMarking': 'Quick marking',
      'coldStartEmpty': 'No high-frequency words to mark right now.',
      'coldStartProgress': '{current} / {total}',
      'coldStartKnownRecognized': 'Know it & hear it',
      'coldStartKnownNotRecognized': 'Know it, can\'t hear it',
      'coldStartUnknownMeaning': 'Don\'t know it',
      'coldStartSkip': 'Skip',
      'mediaLibrary': 'Media library',
      'mediaLibraryEmpty': 'Media you open will appear here.',
      'queueIntensive': 'Intensive picks',
      'queueExtensive': 'Extensive listening',
      'queueDeferred': 'Set aside for now',
      'queueUnsorted': 'Not rated yet',
      'goldenTargetBadge': 'Intensive pick',
      'familiarRelistenBadge': 'Relisten',
      'startExtensiveAction': 'Listen',
      'startIntensiveAction': 'Work on it',
      'pinExtensiveAction': 'Pin to extensive listening',
      'pinIntensiveAction': 'Pin to intensive picks',
      'deferMediaAction': 'Set aside',
      'clearTriageAction': 'Clear pin / set-aside',
      'familiarSuggestionsToggle': 'Suggest relistening familiar material',
      'mediaFileMissing': 'File not found',
      'contentFitWhy': 'Why this rating',
      'contentFitDecisive': 'Drove the rating',
      'fit_signal_unknown_meaning_density': 'Unknown-meaning words',
      'fit_signal_unassessed_density': 'Words not assessed yet',
      'fit_signal_known_not_recognized_density': 'Known but not yet caught by ear',
      'fit_signal_speech_rate_wpm': 'Speech rate',
      'fit_signal_weak_form_density': 'Weak-form density',
      'fit_signal_compression_density': 'Compression density',
      'fit_signal_mean_chunk_length': 'Average chunk length',
      'fit_signal_comprehension_report_unclear_ratio':
          'Sessions you reported as unclear',
      'fit_signal_practice_correct_rate': 'Your practice accuracy',
      'noSubtitleResources': 'No subtitle resources yet',
      'activeSubtitle': 'Active subtitle',
      'activateSubtitle': 'Activate subtitle',
      'sentenceTiming': 'Sentence',
      'wordTiming': 'Word',
      'chunkTiming': 'Chunk',
      'phoneTiming': 'Phone',
      'resourcePartial': 'Partial',
      'resourceLearningCapabilities': 'Learning capabilities',
      'resourceReady': 'Ready to use',
      'resourceArchived': 'Archived',
      'technicalDetails': 'Technical details',
      'resourceTimelineDetailsBelow': 'Details below',
      'resourceActivateToInspect': 'Activate to inspect',
      'diagnosisSummary': 'Summary',
      'diagnosisEvidence': 'Evidence and analysis',
      'diagnosisNoConclusion': 'No specific listening barrier identified.',
      'resourceActions': 'Resource actions',
      'archiveResource': 'Archive resource',
      'restoreResource': 'Restore resource',
      'deleteResource': 'Delete resource',
      'exportSubtitle': 'Export subtitle',
      'exportSubtitleFormat': 'Export subtitle format',
      'exportLLTimelineJson': 'Export LLTimeline JSON',
      'deleteSubtitleResourceBody':
          'Delete this subtitle resource and its attached timelines from the local library?',
      'cues': 'cues',
      'timelineFingerprintMismatch': 'Timeline media mismatch',
      'timelineFingerprintMismatchBody':
          'This LLTimeline resource was produced for a different media fingerprint. Attach it only if you know it matches the current media.',
      'attachAnyway': 'Attach anyway',
      'previousSentence': 'Previous sentence',
      'nextSentence': 'Next sentence',
      'restartMedia': 'Restart media',
      'playPause': 'Play / pause',
      'stop': 'Stop',
      'stopSourceLoop': 'Stop loop',
      'loopRange': 'Range loop',
      'loopOccurrence': 'Source loop',
      'loopReview': 'Review loop',
      'compactMediaPane': 'Compact media pane',
      'resetWorkbenchLayout': 'Reset media/transcript split',
      'audioTrack': 'Audio track',
      'embeddedSubtitles': 'Embedded subtitles',
      'primaryOffset': 'Primary offset',
      'secondaryOffset': 'Secondary offset',
      'generateSubtitles': 'Generate subtitles',
      'generateWholeMedia': 'Generate whole media',
      'primarySubtitleGenerationStarted':
          'Subtitle generation started. The generated primary subtitles will load when the job completes.',
      'secondarySubtitleGenerationStarted':
          'Subtitle generation started. The generated secondary subtitles will load when the job completes.',
      'loadingGeneratedPrimarySubtitle':
          'Loading generated primary subtitles...',
      'generatedPrimarySubtitleLoaded': 'Generated primary subtitles loaded',
      'generatedSecondarySubtitleLoaded':
          'Generated secondary subtitles loaded',
      'generatedSubtitleResourceWarning':
          'Some learning resources need attention',
      'generatePrimaryHint':
          'The completed track will be available as the primary subtitle.',
      'generateSecondaryHint':
          'The completed track will be available as the secondary subtitle.',
      'transcriptionCenter': 'ASR models and jobs',
      'models': 'Models',
      'model': 'Model',
      'jobs': 'Jobs',
      'modelRequired': 'A transcription model is required',
      'installModelFirst':
          'Open ASR models and jobs, then install or register a compatible model.',
      'transcriptionLanguage': 'Recognition language',
      'automatic': 'Automatic detection',
      'translateEnglish': 'Translate speech to English',
      'multilingual': 'Multilingual',
      'registerCustomModel': 'Register custom model',
      'install': 'Install',
      'remove': 'Remove',
      'archive': 'Archive',
      'retry': 'Retry',
      'noTranscriptionJobs': 'No transcription jobs',
      'loadGeneratedSubtitle': 'Load generated subtitle',
      'transcriptionDefaults': 'Transcription defaults',
      'phoneticAnalysis': 'Experimental audio detection',
      'phoneticAnalysisCenter': 'Audio analysis models and jobs',
      'experimental': 'Experimental',
      'applicationVerified': 'Application verified',
      'notApplicationVerified': 'Not application verified',
      'distributionAllowed': 'Distribution allowed',
      'distributionNotAllowed': 'Distribution not allowed',
      'noPhoneticAnalysisJobs': 'No audio analysis jobs',
      'clearCompleted': 'Clear completed',
      'deleteJob': 'Delete',
      'jobCompleted': 'Completed',
      'jobFailed': 'Failed',
      'jobCancelled': 'Cancelled',
      'jobInterrupted': 'Interrupted',
      'jobQueued': 'Queued',
      'jobExtracting': 'Extracting audio',
      'jobRecognizingPhones': 'Recognizing phones',
      'jobAligning': 'Aligning',
      'jobAnalyzing': 'Analyzing',
      'confirmClearJobs': 'Clear all completed, failed, and cancelled jobs?',
      'confirmDeleteJob': 'Delete this job?',
      'phoneticAnalysisPreference': 'Analysis preference',
      'phoneticOnDemand': 'On demand',
      'phoneticBatch': 'Batch analysis',
      'disabled': 'Disabled',
      'phonemeRibbonVisible': 'Show text phoneme ribbon',
      'soundPatternRibbonVisible': 'Show sound reference',
      'soundPatternDisplayMode': 'Sound reference',
      'rhythmReferenceCitation': 'A · Dictionary',
      'rhythmReferenceConnected': 'B · Common speech',
      'rhythmReferenceActual': 'C · This audio',
      'rhythmReferenceCitationTooltip':
          'A · Dictionary pronunciation and lexical stress',
      'rhythmReferenceConnectedTooltip':
          'B · Common connected-speech changes predicted by language rules',
      'rhythmReferenceActualTooltip':
          'C · Heard information anchors supported by this audio',
      'connectedSpeechReference': 'Common speech',
      'connectedSpeechReferenceTooltip':
          'Rule annotations on the sentence: common weak forms, linking and reductions.',
      'connectedSpeechUnavailable': 'No common speech change for this line',
      'citationPronunciationUnavailable':
          'No dictionary pronunciation for this line',
      'showPhoneEvidence': 'Show phone evidence',
      'hidePhoneEvidence': 'Hide phone evidence',
      'phonemeRibbonStyle': 'Ribbon display style',
      'phonemeRibbonWindow': 'Sliding window',
      'phonemeRibbonWave': 'Wave magnification',
      'textPhonemeRibbonHint':
          'Text line: stable teaching phones from the subtitle words.',
      'soundPatternRibbonHint':
          'Listening layer: structure first, phone evidence as detail.',
      'soundPatternUnavailable': 'No phone evidence for this line',
      'soundPatternUnavailableTooltip':
          'Phone evidence appears after audio analysis or an imported timeline provides it for the current sentence.',
      'rhythmFrameUnavailable': 'No listening structure for this line',
      'rhythmRibbonHint':
          'Heard structure: meaning anchors you can catch from this audio; faint weak groups recede into the path.',
      'expectedPronunciationReference': 'Expected',
      'expectedPronunciationTooltip':
          'Dictionary pronunciation reference for the current sentence.',
      'analyzeRealPronunciation': 'Analyze audio pronunciation',
      'analyzeSubtitleTrack': 'Analyze subtitle track',
      'canonicalPronunciation': 'Canonical pronunciation',
      'rulePrediction': 'Rule prediction',
      'audioDetectionExperimental': 'Audio detection (experimental)',
      'listeningRhythm': 'Listening structure',
      'listeningPredictedBadge': 'predicted',
      'listeningPredictedTooltip':
          'Predicted from text, not measured from this audio. Listening structure becomes audio-supported once word timing, energy or pitch evidence exists.',
      'stressAnchors': 'Heard anchors',
      'weakGroups': 'Weak groups',
      'compressedSpans': 'Compressed',
      'listeningHotspots': 'Hotspots',
      'rhythmQuality': 'Rhythm confidence',
      'currentDetectedPhone': 'Current detected phone',
      'loopEvidence': 'Loop evidence',
      'feedbackConfirmed': 'Matches what I hear',
      'feedbackRejected': 'Inaccurate',
      'feedbackIgnored': 'Ignore',
      'preferredQuality': 'Preferred quality',
      'defaultDestination': 'Default subtitle destination',
      'exportSrt': 'Export SRT',
      'regenerate': 'Regenerate with current algorithms',
      'runtimeReady': 'Runtime ready',
      'learningAssets': 'Learning assets',
      'resources': 'Offline learning data',
      'words': 'Words',
      'phones': 'Phones',
      'chunks': 'Chunks',
      'phrases': 'Phrases',
      'word': 'Word',
      'phrase': 'Phrase',
      'phraseCandidates': 'Phrase candidates',
      'phraseCandidatesHint':
          'Review fixed expressions from the current subtitle sentence. Only phrases you save become learning assets.',
      'noPhraseCandidates': 'No phrase candidates in the current sentence.',
      'confirmPhrase': 'Save phrase',
      'openSubtitles': 'Search OpenSubtitles',
      'openSubtitlesApiKey': 'OpenSubtitles API key',
      'openMediaForSubtitles': 'Open a media file before searching subtitles.',
      'configureOpenSubtitlesNow':
          'Enter your OpenSubtitles API key to continue.',
      'search': 'Search',
      'title': 'Title',
      'filename': 'Filename',
      'mediaHash': 'Media hash',
      'lemmaCorrectionSaved': 'Lemma correction saved',
      'configureOpenSubtitles':
          'Configure an OpenSubtitles API key in Settings',
      'pronunciation': 'Play pronunciation',
      'pronunciationUnavailable': 'Pronunciation audio is unavailable.',
      'highlightCurrentWord': 'Highlight current word',
      'showChunkGrouping': 'Group subtitle into chunks',
      'showSenseGrouping': 'Show sense group boundaries',
      'chunkDisplayStyle': 'Chunk display style',
      'chunkDisplayCapsule': 'Capsules',
      'chunkDisplaySpacing': 'Spacing only',
      'highlightCurrentChunk': 'Highlight current chunk',
      'chunkHighlightStyle': 'Current-chunk highlight style',
      'chunkHighlightBackground': 'Static background',
      'chunkHighlightBounce': 'Slow scale bounce',
      'chunkHighlightGlow': 'Slow glow',
      'wordHighlightStyle': 'Current-word highlight style',
      'wordHighlightBackground': 'Background highlight',
      'wordHighlightBounce': 'Scale bounce',
      'wordHighlightGlow': 'Glow',
      'wordHighlightIntensity': 'Current-word highlight intensity',
      'ruleHints': 'Rule hints',
      'ruleHintsOff': 'Off',
      'ruleHintsLikely': 'Likely only',
      'ruleHintsAll': 'All',
      'rulePredictionDisclaimer':
          'Rule predictions, not detections from the audio:',
      'diagnosis_meaning_barrier':
          'Unknown vocabulary may block understanding.',
      'diagnosis_recognition_barrier':
          'Known vocabulary was not recognized in this sentence.',
      'diagnosis_insufficient_information':
          'Classify the remaining words before drawing a conclusion.',
      'diagnosis_other_factors':
          'Vocabulary does not fully explain the listening difficulty.',
      'characters': 'Characters',
      'possibleListeningFactors': 'Factors to consider (not detected):',
      'diagnosis_reason_tone_confusion': 'tone confusion',
      'diagnosis_reason_word_boundary': 'word boundary',
      'diagnosis_reason_homophone': 'homophone',
      'diagnosis_reason_neutral_tone': 'neutral tone',
      'diagnosis_reason_tone_sandhi': 'tone sandhi',
      'diagnosis_reason_weak_form': 'weak form',
      'diagnosis_reason_linking': 'linking',
      'diagnosis_reason_elision': 'elision',
      'diagnosis_reason_assimilation': 'assimilation',
      'diagnosis_reason_fuzzy_boundary': 'fuzzy boundary',
      'diagnosis_reason_reduced_form': 'reduced form',
      'timelineResource': 'Timeline resource',
      'capabilityReadiness': 'Learning capabilities',
      'capabilityStateAvailable': 'Available',
      'capabilityStateGenerating': 'Generating',
      'capabilityStateDegraded': 'Degraded',
      'capabilityStateUnavailable': 'Unavailable',
      'capabilityStateUnsupported': 'Unsupported',
      'capabilityStateStale': 'Stale',
      'capabilityStateError': 'Error',
      'capabilitySubtitles': 'Subtitles',
      'capabilityWordSync': 'Word sync',
      'capabilityChunkReplay': 'Chunk replay',
      'capabilityListeningStructure': 'Listening structure',
      'capabilityPhoneEvidence': 'Phone evidence',
      'capSubtitlesAvailable': 'Active subtitle track loaded.',
      'capSubtitlesArchived': 'This active subtitle is archived.',
      'capSubtitlesUnavailable':
          'Import, generate, search, extract, or attach subtitles.',
      'capWordSyncAvailable': 'Word-level timing is active.',
      'capWordSyncEstimated':
          'Word timing is estimated; highlights may be approximate.',
      'capWordSyncUnavailableNoSubtitle':
          'Load subtitles before word sync can run.',
      'capWordSyncUnavailable':
          'Needs an active Word sync timeline or generated word timings.',
      'capWordSyncGeneratedTimings': 'Generated word timings are loaded.',
      'capChunkReplayAvailable': 'Chunk replay is ready.',
      'capChunkReplayUnavailableNoSubtitle':
          'Load subtitles before chunk replay can run.',
      'capChunkReplayUnavailableNoWord':
          'Generate or attach Word sync before chunk replay.',
      'capChunkReplayUnavailable': 'Generate chunks from the active Word sync.',
      'capListeningAvailable': 'Document listening structure is ready.',
      'capListeningPredictedOnly':
          'Predicted or estimated cues only; not measured audio.',
      'capListeningUnavailableNoSubtitle':
          'Load subtitles before listening structure can run.',
      'capListeningUnavailableNoWord':
          'Needs Word sync before listening structure can be created.',
      'capListeningUnavailable':
          'No listening structure resource yet. Refresh or import a timeline resource.',
      'capPhoneEvidenceAvailable': 'Detailed phone evidence is ready.',
      'capPhoneEvidenceUnavailableNoSubtitle':
          'Load subtitles before phone evidence can run.',
      'capPhoneEvidenceUnavailable':
          'Run audio analysis or import a timeline with phone evidence.',
      'capTimelineResourceError':
          'Timeline refresh failed. Fix the issue, then refresh.',
      'frames': 'frames',
      'importLLTimeline': 'Import LLTimeline',
      'refresh': 'Refresh',
      'lltimelinePresent': 'LLTimeline present',
      'legacyTimelineFallback': 'Legacy timing fallback',
      'humanReviewed': 'Human reviewed',
      'productionReportReady': 'Production report ready',
      'productionReportMissing': 'Production report missing',
      'noTimelineCandidates': 'No Word sync candidates',
      'noPhoneTimelineCandidates': 'No Phone evidence candidates',
      'noChunkTimelineCandidates': 'No Chunk replay candidates',
      'activeTimelineLegacy': 'Word sync: legacy word timings',
      'activeTimelineGeneratedTiming': 'Word sync: generated word timings',
      'activePhoneTimelineMissing':
          'Phone evidence: unavailable until audio analysis runs',
      'activeChunkTimelineMissing': 'Chunk replay: unavailable until generated',
      'activeTimeline': 'Active timeline',
      'activateTimeline': 'Activate timeline',
      'generateChunks': 'Generate chunks',
      'manualReview': 'Manual review',
      'manualReviewQueued': 'Manual review entry is ready for Phase 2.3.',
    },
    'zh': {
      'settings': '设置',
      'moreActions': '更多操作',
      'playbackSettings': '播放设置',
      'general': '通用',
      'resourceSettings': '资源与转写',
      'externalToolsShort': '外部工具',
      'rate': '播放速度',
      'language': '界面语言',
      'system': '跟随系统',
      'english': 'English',
      'chinese': '简体中文',
      'japanese': '日本語',
      'learningLanguage': '学习语言',
      'subtitles': '字幕',
      'subtitlePreset': '字幕预设',
      'watching': '观影模式',
      'learning': '学习模式',
      'compact': '紧凑模式',
      'subtitleScale': '主字幕字号',
      'secondaryScale': '副字幕字号',
      'primaryFont': '主字幕字体',
      'secondaryFont': '副字幕字体',
      'systemFont': '系统字体',
      'serifFont': '衬线字体',
      'monospaceFont': '等宽字体',
      'horizontalPosition': '水平位置',
      'verticalPosition': '垂直位置',
      'resetSubtitlePosition': '重置字幕位置',
      'dragSubtitleHint': '拖动字幕可调整位置',
      'backgroundOpacity': '背景透明度',
      'transcriptWidth': '文稿宽度',
      'primaryColor': '主字幕颜色',
      'secondaryColor': '副字幕颜色',
      'externalTools': '可选外部工具',
      'close': '关闭',
      'save': '保存',
      'vocabulary': '词汇本',
      'home': '首页',
      'library': '内容库',
      'listenNow': '开始',
      'myLearning': '我的学习',
      'continueLearning': '继续学习',
      'continuePlayback': '继续播放',
      'noRecentMedia': '还没有最近媒体',
      'openMediaToContinue': '打开本地媒体后即可开始或继续听力。',
      'subtitleReadiness': '字幕状态',
      'notReadyYet': '未就绪',
      'savedWords': '已存词条',
      'localCore': '本地核心',
      'coreReady': '就绪',
      'startListening': '开始聆听',
      'learningTools': '学习资料',
      'contentActions': '内容',
      'subtitleActions': '字幕',
      'learningActions': '学习',
      'localSource': '本机视频或音频',
      'onlineSource': '打开支持的在线地址',
      'subtitleResourceSummary': '字幕与时间轴资源',
      'vocabularySummary': '听力过程中保存的词与短语',
      'review': '复习',
      'audioFirstReview': '声音优先的到期卡片',
      'noMediaSelected': '尚未选择媒体',
      'openMedia': '打开媒体',
      'openUrl': '打开网址',
      'primarySubtitle': '主字幕',
      'secondarySubtitle': '副字幕',
      'noSecondarySubtitle': '无副字幕',
      'transcript': '字幕文稿',
      'wordLearning': '词汇学习',
      'diagnosis': '句子诊断',
      'practice': '测一下',
      'understandPosture': '听懂了吗？',
      'testPosture': '测一下？',
      'shadowPosture': '跟一下？',
      'shadowingPlannedTooltip': '跟读与录音会在 Phase 3.8 点亮。',
      'selectWordFromTranscript': '在字幕文稿中点击单词后，可查看状态、释义和来源例句。',
      'diagnosisUnavailable': '暂无听感参照',
      'openSentenceDiagnosisHint': '载入字幕后，打开当前句即可查看词汇状态和听感参照。',
      'clozePractice': '挖空',
      'chunkDictation': '语块听写',
      'sentenceDictation': '整句听写',
      'practiceClozeTooltip': '挖掉一个已掌握词，用声音验证是否真的听出。',
      'practiceClozeUnavailable': '挖空需要词级时间轴。',
      'practiceChunkTooltip': '听当前语块并输入听到的内容。',
      'practiceChunkFallbackTooltip': '当前句没有可用语块，将回退到整句听写。',
      'practiceNeedsSentence': '打开一个字幕句后即可练习。',
      'practiceChoosePrompt': '为当前句选择挖空或听写。',
      'markStuckPoint': '标记卡点',
      'skipStuckPoint': '跳过',
      'practiceEstimatedTiming': '当前时间轴为估算，复听窗口可能不够精确。',
      'practiceListenThenType': '先听音频，再输入你听到的内容。',
      'practiceHiddenText': '提交前答案不会显示。',
      'practiceAnswer': '你的答案',
      'createReviewOnFailure': '失败时存入复习',
      'submit': '提交',
      'replay': '复听',
      'retryPractice': '再练一次',
      'openDiagnosis': '加载参照',
      'saveToReview': '存入复习',
      'savedToReview': '已存复习',
      'practiceResult': '结果',
      'practiceCorrect': '正确',
      'practicePartial': '部分匹配',
      'practiceIncorrect': '还没听出',
      'practiceSkipped': '已跳过',
      'sessionSummary': '本次总结',
      'finishIntensive': '精听完毕',
      'intensiveFinished': '已完毕',
      'finishIntensiveWithOpen': '还有 {count} 个未处理卡点，仍然结束吗？',
      'startExtensiveListening': '开始泛听',
      'finishExtensiveListening': '结束泛听',
      'listeningMode': '泛听',
      'extensiveListeningActive': '泛听进行中',
      'extensiveListeningIdle': '泛听未开始',
      'markListeningInbox': '标记到 Listening Inbox',
      'hardInterruptListening': '暂停查看',
      'listeningInbox': 'Listening Inbox',
      'listeningInboxEmpty': '还没有标记的泛听片段。',
      'comprehensionReportPrompt': '这次泛听理解得怎么样？',
      'skipReport': '跳过',
      'reportUnderstoodAll': '全懂',
      'reportGist': '大意懂了',
      'reportUnclear': '迷糊',
      'microIntensive': '微精听',
      'favoriteSegment': '收藏片段',
      'dismissInboxItem': '归档',
      'summaryStuck': '卡住',
      'summaryResolved': '解决',
      'summaryVerified': '验证',
      'summaryReview': '复习',
      'summaryUnexplained': '悬案',
      'openStuckPoints': '悬案区',
      'closeStuckPoint': '关闭',
      'familiarMaterialMarked': '已标记为熟料。',
      'expected': '应为',
      'youTyped': '你写的是',
      'possibleWhy': '可能原因',
      'noWordSelected': '点击字幕单词以打开学习详情。',
      'dictionary': '词典',
      'noDictionary': '暂无词典结果',
      'userDefinition': '自定义释义',
      'personalNote': '个人笔记',
      'sources': '来源原句',
      'statusHistory': '状态历史',
      'currentStatus': '当前状态',
      'learningState': '学习状态',
      'meaningAndPronunciation': '释义与发音',
      'sourceSentences': '来源原句',
      'learningHistory': '学习记录',
      'noSourceSentences': '暂时没有记录来源原句。',
      'recordCurrentSentence': '记录当前句',
      'noLearningHistory': '暂时没有学习记录。',
      'earlier': '较早记录',
      'clear': '清除状态',
      'unknown_meaning': '不认识',
      'known_not_recognized': '认识但听不出',
      'known_recognized': '已掌握',
      'unassessed': '尚未评估',
      'not_acquired': '未掌握',
      'acquired': '已掌握',
      'capabilityReading': '阅读',
      'capabilityListening': '听力',
      'capabilitySpeaking': '口语',
      'capabilityWriting': '写作',
      'capabilityProfile': '能力画像',
      'listeningUpgradeSuggestion': '"{word}" 已在 {count} 个语境中听出，要标为听力已掌握吗？',
      'confirmListeningAcquired': '确认：已能听出',
      'deferUpgrade': '暂不升级',
      'apply': '应用',
      'heard': '本句：听出来了',
      'notHeard': '本句：没有听出',
      'importWordList': '导入已有词表',
      'importAssets': '导入词汇资产',
      'exportAssets': '导出词汇资产',
      'overwriteExisting': '覆盖已有状态',
      'previewImport': '导入预览',
      'import': '导入',
      'noWords': '该词汇本暂无词汇',
      'searchVocabulary': '搜索词汇',
      'vocabularyBooks': '动态词汇本',
      'loopSentence': '循环当前句',
      'previousChunk': '上一语块',
      'nextChunk': '下一语块',
      'chunkMode': '语块',
      'loopChunk': '循环语块',
      'expandChunk': '展开语块',
      'subtitleMode': '字幕',
      'chunkReplayUnavailableControl': '当前句需要可用语块后才能复听。',
      'wordStyles': '词汇状态样式',
      'secondary': '副字幕',
      'secondarySubtitleUnavailable': '请先载入副字幕轨。',
      'noMediaControlsHint': '打开媒体后可使用播放控制',
      'taskSubtitleGeneration': '字幕生成',
      'taskAudioAnalysis': '音素证据分析',
      'taskStateWorking': '进行中',
      'taskStateSuccess': '已完成',
      'taskStateWarning': '需处理',
      'taskStateError': '失败',
      'taskStateCancelled': '已取消',
      'taskStateUnknown': '未知',
      'currentSentenceDiagnosis': '听感参照',
      'pronunciationProvider': '发音来源',
      'wordTimingSource': '词级时间来源',
      'pronunciationCache': '发音缓存',
      'cacheReusable': '可复用',
      'ready': '可用',
      'degraded': '降级',
      'providerUnavailable': '词典来源不可用',
      'noSourceSnapshot': '暂无来源原句',
      'encountered': '遇见',
      'times': '次',
      'openOnlineTitle': '使用 yt-dlp 打开在线媒体',
      'pageUrl': '页面网址',
      'addSource': '添加来源',
      'pasteSourceLink': '粘贴视频或音频链接',
      'recognizedSource': '识别到的来源',
      'youtubeSource': 'YouTube',
      'webSource': '网页地址',
      'playOnline': '在线播放',
      'downloadLocal': '下载到本机',
      'sourceAuthorizationNotice': '仅添加你有权访问的内容，并遵守来源平台的使用条款。',
      'invalidSourceUrl': '请输入有效的 http 或 https 地址。',
      'cancel': '取消',
      'resolvePlay': '解析并播放',
      'download': '下载',
      'downloadVideo': '下载视频',
      'downloadHere': '下载到此处',
      'startingDownload': '正在开始下载...',
      'downloadingVideo': '正在下载视频',
      'downloadComplete': '下载完成',
      'downloadFailed': '下载失败',
      'downloadCancelled': '下载已取消',
      'downloadingInBackground': '正在后台下载',
      'openDownloadedVideo': '打开已下载视频',
      'importEmbeddedText': '导入内嵌文本字幕',
      'usePrimary': '作为主字幕',
      'useSecondary': '作为副字幕',
      'exportLogs': '导出日志',
      'archiveMedia': '归档当前媒体',
      'openVideoAudio': '打开视频或音频',
      'importSubtitle': '导入字幕',
      'importSubtitleHint': '导入 SRT 或 WebVTT 字幕',
      'noTranscriptTitle': '还没有文稿',
      'backToCurrentSentence': '回到当前句',
      'subtitleResources': '字幕资源',
      'contentFit': '难度适配',
      'contentFitMeaning': '词汇',
      'contentFitSound': '语音',
      'fit_too_easy': '轻松',
      'fit_comprehensible': '合适',
      'fit_challenging': '有挑战',
      'fit_too_hard': '需要辅助',
      'contentFitIntensiveTarget': '你大概率看得懂，功夫在听辨上——适合精听的材料。',
      'contentFitInitialEstimate': '初始估计',
      'contentFitCalibrated': '已按你的使用校准',
      'contentFitLowProfile': '词汇画像对这段材料的覆盖还很少，这是保守估计——先标注一些词会更准。',
      'coldStartQuickMarking': '快速标注',
      'coldStartEmpty': '目前没有需要标注的高频词。',
      'coldStartProgress': '{current} / {total}',
      'coldStartKnownRecognized': '认识也听得出',
      'coldStartKnownNotRecognized': '看得懂听不出',
      'coldStartUnknownMeaning': '不认识',
      'coldStartSkip': '跳过',
      'mediaLibrary': '媒体库',
      'mediaLibraryEmpty': '打开过的媒体会出现在这里。',
      'queueIntensive': '精听靶单',
      'queueExtensive': '泛听队列',
      'queueDeferred': '暂缓区',
      'queueUnsorted': '未分级',
      'goldenTargetBadge': '精听靶',
      'familiarRelistenBadge': '熟料回听',
      'startExtensiveAction': '泛听',
      'startIntensiveAction': '精听',
      'pinExtensiveAction': '固定到泛听队列',
      'pinIntensiveAction': '固定到精听靶单',
      'deferMediaAction': '暂缓',
      'clearTriageAction': '清除固定 / 暂缓',
      'familiarSuggestionsToggle': '建议回听熟悉材料',
      'mediaFileMissing': '文件已不存在',
      'contentFitWhy': '依据',
      'contentFitDecisive': '影响档位',
      'fit_signal_unknown_meaning_density': '生词密度',
      'fit_signal_unassessed_density': '未标注词比例',
      'fit_signal_known_not_recognized_density': '看得懂听不出的词',
      'fit_signal_speech_rate_wpm': '语速',
      'fit_signal_weak_form_density': '弱读密度',
      'fit_signal_compression_density': '压缩密度',
      'fit_signal_mean_chunk_length': '平均意群长度',
      'fit_signal_comprehension_report_unclear_ratio': '你自报"没听懂"的比例',
      'fit_signal_practice_correct_rate': '你的练习正确率',
      'noSubtitleResources': '暂无字幕资源',
      'activeSubtitle': '当前字幕',
      'activateSubtitle': '激活字幕',
      'sentenceTiming': '句级',
      'wordTiming': '词级',
      'chunkTiming': '分块',
      'phoneTiming': '音素',
      'resourcePartial': '部分可用',
      'resourceLearningCapabilities': '学习能力',
      'resourceReady': '可以使用',
      'resourceArchived': '已归档',
      'technicalDetails': '技术详情',
      'resourceTimelineDetailsBelow': '详情见下方',
      'resourceActivateToInspect': '激活后检查',
      'diagnosisSummary': '诊断摘要',
      'diagnosisEvidence': '证据与分析',
      'diagnosisNoConclusion': '暂未发现明确的听辨障碍。',
      'resourceActions': '资源操作',
      'archiveResource': '归档资源',
      'restoreResource': '恢复资源',
      'deleteResource': '删除资源',
      'exportSubtitle': '导出字幕',
      'exportSubtitleFormat': '选择导出字幕格式',
      'exportLLTimelineJson': '导出 LLTimeline JSON',
      'deleteSubtitleResourceBody': '从本地资源库删除这个字幕资源及其关联时间轴？',
      'cues': '句',
      'timelineFingerprintMismatch': '时间轴媒体不匹配',
      'timelineFingerprintMismatchBody':
          '这个 LLTimeline 资源来自不同的媒体 fingerprint。只有在你确认它匹配当前媒体时才应挂载。',
      'attachAnyway': '仍然挂载',
      'previousSentence': '上一句',
      'nextSentence': '下一句',
      'restartMedia': '重新播放媒体',
      'playPause': '播放 / 暂停',
      'stop': '停止',
      'stopSourceLoop': '停止循环',
      'loopRange': '范围循环',
      'loopOccurrence': '来源循环',
      'loopReview': '复查循环',
      'compactMediaPane': '压缩视频区',
      'resetWorkbenchLayout': '重置媒体/文稿比例',
      'audioTrack': '音轨',
      'embeddedSubtitles': '内嵌字幕',
      'primaryOffset': '主字幕偏移',
      'secondaryOffset': '副字幕偏移',
      'generateSubtitles': '生成字幕',
      'generateWholeMedia': '生成完整媒体字幕',
      'primarySubtitleGenerationStarted': '字幕生成已开始。任务完成后会自动载入为主字幕。',
      'secondarySubtitleGenerationStarted': '字幕生成已开始。任务完成后会自动载入为副字幕。',
      'loadingGeneratedPrimarySubtitle': '正在载入生成的主字幕...',
      'generatedPrimarySubtitleLoaded': '已载入生成的主字幕',
      'generatedSecondarySubtitleLoaded': '已载入生成的副字幕',
      'generatedSubtitleResourceWarning': '部分学习资源需要处理',
      'generatePrimaryHint': '完成后可作为主字幕载入。',
      'generateSecondaryHint': '完成后可作为副字幕载入。',
      'transcriptionCenter': 'ASR 模型与任务',
      'models': '模型',
      'model': '模型',
      'jobs': '任务',
      'modelRequired': '需要转录模型',
      'installModelFirst': '请先在 ASR 模型与任务中安装或注册兼容模型。',
      'transcriptionLanguage': '识别语言',
      'automatic': '自动检测',
      'translateEnglish': '翻译为英文',
      'multilingual': '多语言',
      'registerCustomModel': '注册自定义模型',
      'install': '安装',
      'remove': '删除',
      'archive': '归档',
      'retry': '重试',
      'noTranscriptionJobs': '暂无转录任务',
      'loadGeneratedSubtitle': '载入生成字幕',
      'transcriptionDefaults': '转录默认设置',
      'phoneticAnalysis': '实验性音频检测',
      'phoneticAnalysisCenter': '音频分析模型与任务',
      'experimental': '实验性',
      'applicationVerified': '已通过应用验证',
      'notApplicationVerified': '未通过应用验证',
      'distributionAllowed': '允许分发',
      'distributionNotAllowed': '不允许分发',
      'noPhoneticAnalysisJobs': '暂无音频分析任务',
      'clearCompleted': '清除已完成',
      'deleteJob': '删除',
      'jobCompleted': '已完成',
      'jobFailed': '失败',
      'jobCancelled': '已取消',
      'jobInterrupted': '已中断',
      'jobQueued': '排队中',
      'jobExtracting': '提取音频中',
      'jobRecognizingPhones': '识别音素中',
      'jobAligning': '对齐中',
      'jobAnalyzing': '分析中',
      'confirmClearJobs': '清除所有已完成、失败和已取消的任务？',
      'confirmDeleteJob': '删除此任务？',
      'phoneticAnalysisPreference': '分析偏好',
      'phoneticOnDemand': '按需分析',
      'phoneticBatch': '批量分析',
      'disabled': '禁用',
      'phonemeRibbonVisible': '显示文字线音素带',
      'soundPatternRibbonVisible': '显示听感参照',
      'soundPatternDisplayMode': '听感参照',
      'rhythmReferenceCitation': 'A · 字典读音',
      'rhythmReferenceConnected': 'B · 常见语流',
      'rhythmReferenceActual': 'C · 当前听感',
      'rhythmReferenceCitationTooltip': 'A · 来自字典的读音与词汇重音',
      'rhythmReferenceConnectedTooltip': 'B · 根据语言规则预测的常见连续语流变化',
      'rhythmReferenceActualTooltip': 'C · 当前音频支持的可听信息锚点',
      'connectedSpeechReference': '常见语流',
      'connectedSpeechReferenceTooltip': '直接标注在原句上的常见弱读、连读与缩约规则。',
      'connectedSpeechUnavailable': '当前句没有常见语流变化',
      'citationPronunciationUnavailable': '当前句暂无字典读音',
      'showPhoneEvidence': '查看音素证据',
      'hidePhoneEvidence': '收起音素证据',
      'phonemeRibbonStyle': '音素带显示方式',
      'phonemeRibbonWindow': '滑动窗口',
      'phonemeRibbonWave': '波浪放大',
      'textPhonemeRibbonHint': '文字线：来自字幕单词的稳定教学音素。',
      'soundPatternRibbonHint': '听感层：默认显示听感结构，音素证据作为细节。',
      'soundPatternUnavailable': '当前句暂无音素证据',
      'soundPatternUnavailableTooltip': '音素证据需要当前句已有音频分析，或导入的时间轴资源提供对应证据。',
      'rhythmFrameUnavailable': '当前句暂无听感结构',
      'rhythmRibbonHint': '可听结构：抓住当前音频里能听到的信息锚点，微弱的弱读音团退到背景路径。',
      'expectedPronunciationReference': '预期',
      'expectedPronunciationTooltip': '当前句的词典发音参考。',
      'analyzeRealPronunciation': '分析真实发音',
      'analyzeSubtitleTrack': '分析整条字幕',
      'canonicalPronunciation': '规范发音',
      'rulePrediction': '规则预测',
      'audioDetectionExperimental': '音频检测（实验性）',
      'listeningRhythm': '听感结构',
      'listeningPredictedBadge': '预测',
      'listeningPredictedTooltip': '基于文本预测，非本段音频实测。听感结构需有词级时长、能量或音高证据才算音频支持。',
      'stressAnchors': '可听信息锚点',
      'weakGroups': '弱读音团',
      'compressedSpans': '压缩区',
      'listeningHotspots': '听感热点',
      'rhythmQuality': '节奏置信度',
      'currentDetectedPhone': '当前检测音素',
      'loopEvidence': '循环播放证据',
      'feedbackConfirmed': '符合听感',
      'feedbackRejected': '不准确',
      'feedbackIgnored': '忽略',
      'preferredQuality': '首选质量',
      'defaultDestination': '默认字幕目标',
      'exportSrt': '导出 SRT',
      'regenerate': '使用当前算法重新生成',
      'runtimeReady': '运行时已就绪',
      'learningAssets': '学习资产',
      'resources': '离线学习数据',
      'words': '单词',
      'phones': '音素',
      'chunks': '语块',
      'phrases': '短语',
      'word': '单词',
      'phrase': '短语',
      'phraseCandidates': '短语候选',
      'phraseCandidatesHint': '查看当前字幕句中的固定搭配。只有手动保存的短语才会成为学习资产。',
      'noPhraseCandidates': '当前句没有可用的短语候选。',
      'confirmPhrase': '保存短语',
      'openSubtitles': '搜索 OpenSubtitles',
      'openSubtitlesApiKey': 'OpenSubtitles API Key',
      'openMediaForSubtitles': '请先打开媒体，再搜索字幕。',
      'configureOpenSubtitlesNow': '请输入 OpenSubtitles API Key 以继续。',
      'search': '搜索',
      'title': '标题',
      'filename': '文件名',
      'mediaHash': '媒体哈希',
      'lemmaCorrectionSaved': 'Lemma 修正已保存',
      'configureOpenSubtitles': '请先在设置中配置 OpenSubtitles API Key',
      'pronunciation': '播放发音',
      'pronunciationUnavailable': '发音音频暂时不可用。',
      'highlightCurrentWord': '高亮当前词',
      'showChunkGrouping': '将字幕显示为语块',
      'showSenseGrouping': '显示意群分隔',
      'chunkDisplayStyle': '语块显示方式',
      'chunkDisplayCapsule': '胶囊分组',
      'chunkDisplaySpacing': '仅间距分组',
      'highlightCurrentChunk': '高亮当前语块',
      'chunkHighlightStyle': '当前语块提示方式',
      'chunkHighlightBackground': '静态背景',
      'chunkHighlightBounce': '慢速缩放跳动',
      'chunkHighlightGlow': '慢速发光',
      'wordHighlightStyle': '当前词跳动方式',
      'wordHighlightBackground': '背景高亮',
      'wordHighlightBounce': '放大跳动',
      'wordHighlightGlow': '发光',
      'wordHighlightIntensity': '当前词高亮强度',
      'ruleHints': '语流规则提示',
      'ruleHintsOff': '关闭',
      'ruleHintsLikely': '仅高可能性',
      'ruleHintsAll': '全部',
      'rulePredictionDisclaimer': '以下是规则预测，并非真实音频检测：',
      'diagnosis_meaning_barrier': '不认识的词汇可能阻碍理解。',
      'diagnosis_recognition_barrier': '已认识的词汇在本句中没有被听出。',
      'diagnosis_insufficient_information': '请先判断剩余词汇，再形成结论。',
      'diagnosis_other_factors': '词汇状态不能完全解释当前听力困难。',
      'characters': '字',
      'possibleListeningFactors': '可能涉及的听辨因素（非检测结果）：',
      'diagnosis_reason_tone_confusion': '声调混淆',
      'diagnosis_reason_word_boundary': '词边界切分',
      'diagnosis_reason_homophone': '同音词',
      'diagnosis_reason_neutral_tone': '轻声',
      'diagnosis_reason_tone_sandhi': '变调',
      'diagnosis_reason_weak_form': '弱读',
      'diagnosis_reason_linking': '连读',
      'diagnosis_reason_elision': '省音',
      'diagnosis_reason_assimilation': '同化',
      'diagnosis_reason_fuzzy_boundary': '边界模糊',
      'diagnosis_reason_reduced_form': '弱化形式',
      'timelineResource': '时间轴资源',
      'capabilityReadiness': '学习能力',
      'capabilityStateAvailable': '可用',
      'capabilityStateGenerating': '生成中',
      'capabilityStateDegraded': '降级',
      'capabilityStateUnavailable': '不可用',
      'capabilityStateUnsupported': '不支持',
      'capabilityStateStale': '可能过期',
      'capabilityStateError': '错误',
      'capabilitySubtitles': '字幕',
      'capabilityWordSync': '单词同步',
      'capabilityChunkReplay': '语块复听',
      'capabilityListeningStructure': '听感结构',
      'capabilityPhoneEvidence': '音素证据',
      'capSubtitlesAvailable': '已加载当前字幕轨。',
      'capSubtitlesArchived': '当前字幕已归档。',
      'capSubtitlesUnavailable': '请导入、生成、搜索、提取或挂载字幕。',
      'capWordSyncAvailable': '当前字幕已有词级时间。',
      'capWordSyncEstimated': '词级时间为估计值，高亮可能不精确。',
      'capWordSyncUnavailableNoSubtitle': '需要先加载字幕，才能进行单词同步。',
      'capWordSyncUnavailable': '需要可用的单词同步时间轴或生成的词级时间。',
      'capWordSyncGeneratedTimings': '已加载生成的词级时间。',
      'capChunkReplayAvailable': '语块复听已就绪。',
      'capChunkReplayUnavailableNoSubtitle': '需要先加载字幕，才能进行语块复听。',
      'capChunkReplayUnavailableNoWord': '需要先生成或挂载单词同步。',
      'capChunkReplayUnavailable': '可从当前单词同步生成语块。',
      'capListeningAvailable': '文档级听感结构已就绪。',
      'capListeningPredictedOnly': '仅有预测或估计提示，不是实测音频结论。',
      'capListeningUnavailableNoSubtitle': '需要先加载字幕，才能生成听感结构。',
      'capListeningUnavailableNoWord': '需要单词同步后，才能创建听感结构。',
      'capListeningUnavailable': '暂无听感结构资源。请刷新或导入时间轴资源。',
      'capPhoneEvidenceAvailable': '详细音素证据已就绪。',
      'capPhoneEvidenceUnavailableNoSubtitle': '需要先加载字幕，才能查看音素证据。',
      'capPhoneEvidenceUnavailable': '请运行音频分析，或导入包含音素证据的时间轴。',
      'capTimelineResourceError': '时间轴刷新失败。修复问题后请刷新。',
      'frames': '帧',
      'importLLTimeline': '导入 LLTimeline',
      'refresh': '刷新',
      'lltimelinePresent': '已导入 LLTimeline',
      'legacyTimelineFallback': '旧时间轴降级',
      'humanReviewed': '人工复核',
      'productionReportReady': '生产报告已就绪',
      'productionReportMissing': '暂无生产报告',
      'noTimelineCandidates': '暂无单词同步候选',
      'noPhoneTimelineCandidates': '暂无音素证据候选',
      'noChunkTimelineCandidates': '暂无语块复听候选',
      'activeTimelineLegacy': '单词同步：旧词级时间',
      'activeTimelineGeneratedTiming': '单词同步：已生成词级时间',
      'activePhoneTimelineMissing': '音素证据：需要先运行音频分析',
      'activeChunkTimelineMissing': '语块复听：需要先生成语块',
      'activeTimeline': '当前时间轴',
      'activateTimeline': '激活时间轴',
      'generateChunks': '生成语块',
      'manualReview': '人工复核',
      'manualReviewQueued': '人工复核入口已就绪，完整编辑器将在 Phase 2.3 推进。',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (value) => value.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
